use crate::TurnProcessor;

pub(super) const SEQUENTIAL_TURN_PROCESSORS: [TurnProcessor; 17] = [
    TurnProcessor::Lifecycle,
    TurnProcessor::CityFounding,
    TurnProcessor::WorkerJobs,
    TurnProcessor::Economy,
    TurnProcessor::Production,
    TurnProcessor::Artifacts,
    TurnProcessor::MovementReset,
    TurnProcessor::QueuedMovement,
    TurnProcessor::TradeRoutes,
    TurnProcessor::WorkerAutomation,
    TurnProcessor::AutoExplore,
    TurnProcessor::ReversibleSkipCleanup,
    TurnProcessor::Research,
    TurnProcessor::Diplomacy,
    TurnProcessor::Agreements,
    TurnProcessor::Objectives,
    TurnProcessor::Outcome,
];

pub(super) const SIMULTANEOUS_TURN_PROCESSORS: [TurnProcessor; 19] = [
    TurnProcessor::Submission,
    TurnProcessor::Lifecycle,
    TurnProcessor::Combat,
    TurnProcessor::CityFounding,
    TurnProcessor::WorkerJobs,
    TurnProcessor::Economy,
    TurnProcessor::Production,
    TurnProcessor::Artifacts,
    TurnProcessor::MovementReset,
    TurnProcessor::QueuedMovement,
    TurnProcessor::TradeRoutes,
    TurnProcessor::WorkerAutomation,
    TurnProcessor::AutoExplore,
    TurnProcessor::ReversibleSkipCleanup,
    TurnProcessor::Research,
    TurnProcessor::Diplomacy,
    TurnProcessor::Agreements,
    TurnProcessor::Objectives,
    TurnProcessor::Outcome,
];
