version: 2

updates:
  - package-ecosystem: cargo
    directory: /engine
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /packages/aonw_core
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /packages/aonw_server_client
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: pub
    directory: /server
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:30"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /server
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5
