# Uncomment and fill in the channels you actually use.
# See: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# github: [your-github-username]
# ko_fi: your-ko-fi-username
# custom: ["https://aonw.net"]
