extends RefCounted

const FIELDS := {
	"artifactExcavationStarted": ["type", "artifactId", "ownerPlayerId", "unitId", "coordinate"],
	"artifactCarried": ["type", "artifactId", "ownerPlayerId", "unitId", "coordinate"],
	"artifactStored": ["type", "artifactId", "ownerPlayerId", "sourceUnitId", "cityId", "coordinate"],
	"cityFounded": ["type", "cityId", "ownerPlayerId"],
	"cityBuiltBuilding": ["type", "cityId", "buildingType"],
	"cityProducedUnit": ["type", "cityId", "unitType", "producedUnitId"],
	"cityBuiltWonder": ["type", "cityId", "ownerPlayerId", "wonderType"],
	"wonderProductionRefunded": ["type", "cityId", "ownerPlayerId", "wonderType", "refundedProduction"],
	"technologyResearched": ["type", "playerId", "technologyId"],
	"researchPointsGained": ["type", "playerId", "points"],
	"cityClaimedHex": ["type", "cityId", "col", "row"],
	"stabilityBandChanged": ["type", "playerId", "previousBand", "newBand", "net"],
	"mapObjectiveSecured": ["type", "playerId", "objectiveId", "objectiveType", "col", "row", "holdTurns", "requiredHoldTurns", "victoryPoints", "goldPerTurn"],
	"dominationThresholdReached": ["type", "playerId", "controlPercent", "requiredControlPercent", "holdTurns", "requiredHoldTurns"],
	"matchEnded": ["type", "turn", "outcome"],
	"unitAttacked": ["type", "attackerUnitId", "target"],
	"cityAttacked": ["type", "attackerUnitId", "target"],
	"combatResolved": ["type", "attackerUnitId", "target"],
	"diplomaticScoreChanged": ["type", "playerAId", "playerBId", "delta", "scoreAfter", "reason", "sourceId"],
	"diplomaticProposalSent": ["type", "proposalId", "fromPlayerId", "toPlayerId", "kind", "expiresOnTurn"],
	"diplomaticProposalResponded": ["type", "proposalId", "fromPlayerId", "toPlayerId", "kind", "accepted"],
	"diplomaticProposalExpired": ["type", "proposalId", "fromPlayerId", "toPlayerId", "kind"],
	"diplomaticMessageSent": ["type", "messageId", "fromPlayerId", "toPlayerId", "topic", "category", "expiresOnTurn"],
	"diplomaticMessageResponded": ["type", "messageId", "fromPlayerId", "toPlayerId", "topic", "response", "relationDelta", "relationScoreAfter", "promiseDueTurn"],
	"diplomaticPromiseBroken": ["type", "messageId", "playerAId", "playerBId", "delta", "scoreAfter"],
	"diplomaticRelationChanged": ["type", "playerAId", "playerBId", "oldStatus", "newStatus", "reason", "expiresOnTurn"],
	"unitGainedExperience": ["type", "attackerUnitId", "target", "subjectUnitId"],
	"unitKilled": ["type", "attackerUnitId", "target", "subjectUnitId"],
	"unitRetreated": ["type", "attackerUnitId", "target", "subjectUnitId"],
	"cityCaptured": ["type", "attackerUnitId", "target"],
	"cityDestroyed": ["type", "attackerUnitId", "target"],
	"unitMoved": ["type", "unitId", "from", "to"],
	"autoExplorePlanned": ["type", "unitId", "target"],
	"merchantRouteAssigned": ["type", "unitId", "originCityId", "destinationCityId"],
	"merchantTravelQueued": ["type", "unitId", "destinationCityId"],
	"troopDetached": ["type", "sourceUnitId", "detachedUnitId", "troopKind", "destination"],
	"turnEnded": ["type", "playerId"],
	"allPlayersSubmitted": ["type", "turn", "playerIds"],
	"playerTimedOut": ["type", "turn", "playerId"],
	"playerKicked": ["type", "turn", "playerId", "reason", "timeoutStreak"],
	"workerCompletedJob": ["type", "unitId", "target", "completion"],
}

const TURN_PROCESSORS := [
	"submission", "lifecycle", "combat", "cityFounding", "workerJobs", "economy",
	"production", "artifacts", "movementReset", "queuedMovement", "tradeRoutes",
	"workerAutomation", "autoExplore", "reversibleSkipCleanup", "research",
	"diplomacy", "agreements", "objectives", "outcome",
]
