import 'package:aonw_core/domain.dart';

final presentationDomainCommands = <DomainCommand>[
  const MoveUnitCommand('scout_1', 2, 3),
  const CancelUnitActionCommand('scout_1'),
  const SkipUnitTurnCommand('scout_1'),
  const FortifyUnitCommand('scout_1'),
  const AutoExploreUnitCommand('scout_1'),
  const AutomateWorkerCommand('worker_1'),
  const BuildRoadCommand('worker_1'),
  const AssignMerchantTradeRouteCommand('merchant_1', 'city_2'),
  const MoveMerchantToCityCommand('merchant_1', 'city_2'),
  const StartArtifactExcavationCommand('scout_1'),
  const StoreArtifactInCityCommand('scout_1', cityId: 'city_1'),
  const TradeArtifactCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    offeredArtifactId: 'artifact_1',
  ),
  FoundCityCommand('settler_1', controlledHexes: const []),
  const StartBuildingCommand('city_1', CityBuildingType.granary),
  const StartUnitProductionCommand('city_1', GameUnitType.archer),
  const StartCityProjectCommand('city_1', CityProjectType.research),
  const StartWonderCommand('city_1', WonderType.greatLibrary),
  const SetCitySpecializationCommand('city_1', CitySpecializationType.science),
  const RushProductionCommand('city_1'),
  const SelectTechnologyCommand('player_1', TechnologyId.mining),
  const DetachTroopCommand('army_1', TroopType.archer),
  const EndTurnCommand('player_1'),
  const SubmitTurnCommand('player_1'),
  const SendDiplomaticProposalCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    kind: DiplomaticProposalKind.friendship,
    proposalId: 'proposal_1',
    goldPayment: 6,
  ),
  const RespondDiplomaticProposalCommand(
    playerId: 'player_2',
    proposalId: 'proposal_1',
    accepted: true,
  ),
  const SendDiplomaticMessageCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    topic: DiplomaticMessageTopic.troopsNearCities,
    messageId: 'message_1',
  ),
  const RespondDiplomaticMessageCommand(
    playerId: 'player_2',
    messageId: 'message_1',
    response: DiplomaticMessageResponse.conciliatory,
  ),
  const DeclareWarCommand(playerId: 'player_1', targetPlayerId: 'player_2'),
  const SendGoldGiftCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    amount: 12,
  ),
  const OpenResourceTradeCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    resource: ResourceType.horses,
    goldPerTurn: 3,
    durationTurns: 8,
    agreementId: 'trade_1',
  ),
  const OpenResourceExchangeCommand(
    playerId: 'player_1',
    targetPlayerId: 'player_2',
    offeredResource: ResourceType.iron,
    requestedResource: ResourceType.horses,
    durationTurns: 8,
    agreementId: 'exchange_1',
  ),
  const SelectCityExpansionHexCommand('city_1', 1, 2),
  const ToggleWorkedHexCommand('city_1', 1, 2),
  const SelectWorkerImprovementCommand('worker_1', FieldImprovementType.mine),
  const ConfirmWorkerImprovementCommand('worker_1'),
  const CancelWorkerJobCommand('worker_1'),
  const AssignWorkerToHexCommand('worker_1'),
  const CancelWorkerAssignmentCommand('worker_1'),
  const AttackHexCommand('warrior_1', 4, 5),
];

const presentationGameIntents = <GameIntent>[
  StartCommanderMergeSelectionCommand('commander_1'),
  CancelCommanderMergeSelectionCommand('commander_1'),
  CancelResearchSelectionCommand('player_1'),
  StartWorkerActionSelectionCommand('worker_1'),
  ChooseWorkerImprovementIntent('worker_1', FieldImprovementType.farm),
  ConfirmWorkerImprovementIntent('worker_1'),
  CancelWorkerActionSelectionCommand('worker_1'),
  TileTappedCommand(1, 1),
  CityTappedCommand('city_1'),
  SelectTileCommand(1, 1),
  SelectUnitCommand('unit_1'),
  SelectCityCommand('city_1'),
  FocusNextPendingActionCommand('player_1'),
  FocusTurnStartActionCommand('player_1'),
  StartAttackTargetingCommand('warrior_1'),
  CancelAttackTargetingCommand('warrior_1'),
  StartCityFoundingCommand(),
  CancelCityFoundingCommand(),
  StartCityWorkedHexSelectionCommand('city_1'),
  CancelCityWorkedHexSelectionCommand('city_1'),
  StartCityExpansionSelectionCommand('city_1'),
  CancelCityExpansionSelectionCommand('city_1'),
  StartMerchantTradeRouteSelectionCommand('merchant_1'),
  CancelMerchantTradeRouteSelectionCommand('merchant_1'),
  StartMerchantMoveToCitySelectionCommand('merchant_1'),
  CancelMerchantMoveToCitySelectionCommand('merchant_1'),
  ToggleMoveTargetingCommand(),
];
