import 'package:aonw_core/domain.dart';

final presentationGameEvents = <GameEvent>[
  const ArtifactExcavationStartedEvent(
    artifactId: 'artifact_1',
    ownerPlayerId: 'player_1',
    unitId: 'worker_1',
    col: 1,
    row: 1,
  ),
  const ArtifactCarriedEvent(
    artifactId: 'artifact_1',
    ownerPlayerId: 'player_1',
    unitId: 'worker_1',
    col: 2,
    row: 1,
  ),
  const ArtifactStoredEvent(
    artifactId: 'artifact_1',
    ownerPlayerId: 'player_1',
    unitId: 'worker_1',
    cityId: 'city_1',
    col: 3,
    row: 1,
  ),
  const CityFoundedEvent(cityId: 'city_1', ownerPlayerId: 'player_1'),
  const CityBuiltBuildingEvent(
    cityId: 'city_1',
    buildingType: CityBuildingType.granary,
  ),
  const CityBuiltWonderEvent(
    cityId: 'city_1',
    ownerPlayerId: 'player_1',
    wonderType: WonderType.greatLibrary,
  ),
  const WonderProductionRefundedEvent(
    cityId: 'city_1',
    ownerPlayerId: 'player_1',
    wonderType: WonderType.greatLibrary,
    refundedProduction: 12,
  ),
  const CityProducedUnitEvent(
    cityId: 'city_1',
    unitType: GameUnitType.archer,
    producedUnitId: 'produced_1',
  ),
  const CityClaimedHexEvent(cityId: 'city_1', col: 2, row: 2),
  const UnitAttackedEvent(
    attackerUnitId: 'attacker_1',
    attackerOwnerPlayerId: 'player_1',
    defenderUnitId: 'defender_1',
    defenderOwnerPlayerId: 'player_2',
  ),
  CombatResolvedEvent(
    attackerUnitId: 'attacker_1',
    defenderUnitId: 'defender_1',
    outcome: _combatOutcome,
  ),
  const UnitKilledEvent(
    unitId: 'killed_1',
    ownerPlayerId: 'player_2',
    attackerUnitId: 'attacker_1',
  ),
  const UnitRetreatedEvent(
    unitId: 'defender_1',
    ownerPlayerId: 'player_2',
    fromCol: 2,
    fromRow: 0,
    toCol: 3,
    toRow: 0,
  ),
  const CityAttackedEvent(
    attackerUnitId: 'attacker_1',
    attackerOwnerPlayerId: 'player_1',
    cityId: 'city_2',
    cityOwnerPlayerId: 'player_2',
  ),
  const CityCapturedEvent(
    cityId: 'city_2',
    previousOwnerPlayerId: 'player_2',
    newOwnerPlayerId: 'player_1',
  ),
  const CityDestroyedEvent(
    cityId: 'city_2',
    previousOwnerPlayerId: 'player_2',
    attackerOwnerPlayerId: 'player_1',
  ),
  const DiplomaticProposalSentEvent(
    proposalId: 'proposal_1',
    fromPlayerId: 'player_1',
    toPlayerId: 'player_2',
    kind: DiplomaticProposalKind.friendship,
    expiresOnTurn: 8,
  ),
  const DiplomaticProposalRespondedEvent(
    proposalId: 'proposal_1',
    fromPlayerId: 'player_1',
    toPlayerId: 'player_2',
    kind: DiplomaticProposalKind.friendship,
    accepted: true,
  ),
  const DiplomaticProposalExpiredEvent(
    proposalId: 'proposal_2',
    fromPlayerId: 'player_2',
    toPlayerId: 'player_1',
    kind: DiplomaticProposalKind.truce,
  ),
  const DiplomaticRelationChangedEvent(
    playerAId: 'player_1',
    playerBId: 'player_2',
    oldStatus: DiplomaticRelationStatus.neutral,
    newStatus: DiplomaticRelationStatus.friendly,
    reason: DiplomaticRelationChangeReason.proposalAccepted,
    expiresOnTurn: 12,
  ),
  const DiplomaticMessageSentEvent(
    messageId: 'message_1',
    fromPlayerId: 'player_1',
    toPlayerId: 'player_2',
    topic: DiplomaticMessageTopic.troopsNearCities,
    category: DiplomaticMessageCategory.warning,
    expiresOnTurn: 7,
  ),
  const DiplomaticMessageRespondedEvent(
    messageId: 'message_1',
    fromPlayerId: 'player_1',
    toPlayerId: 'player_2',
    topic: DiplomaticMessageTopic.troopsNearCities,
    response: DiplomaticMessageResponse.conciliatory,
    relationDelta: 12,
    relationScoreAfter: 22,
    promiseDueTurn: 9,
  ),
  const DiplomaticScoreChangedEvent(
    playerAId: 'player_1',
    playerBId: 'player_2',
    delta: 5,
    scoreAfter: 27,
    reason: DiplomaticScoreChangeReason.goldGift,
    sourceId: 'gift_1',
  ),
  const DiplomaticPromiseBrokenEvent(
    messageId: 'message_1',
    playerAId: 'player_1',
    playerBId: 'player_2',
    delta: -15,
    scoreAfter: 12,
  ),
  const MapObjectiveSecuredEvent(
    playerId: 'player_1',
    objectiveId: 'objective_1',
    objectiveType: MapObjectiveType.strategicPass,
    col: 2,
    row: 2,
    holdTurns: 3,
    requiredHoldTurns: 3,
    victoryPoints: 2,
    goldPerTurn: 1,
  ),
  const ResearchPointsGainedEvent(playerId: 'player_1', points: 12),
  const TechnologyResearchedEvent(
    playerId: 'player_1',
    technologyId: TechnologyId.mining,
  ),
  const StrategicResourceDiscoveredEvent(
    playerId: 'player_1',
    resourceType: ResourceType.iron,
    controlledCount: 1,
    rivalControlledCount: 1,
    unclaimedCount: 2,
    pressure: StrategicResourceDiscoveryPressure.expansionRace,
    nearestUnclaimedCol: 4,
    nearestUnclaimedRow: 4,
  ),
  const StabilityBandChangedEvent(
    playerId: 'player_1',
    previousBand: StabilityBand.stable,
    newBand: StabilityBand.strained,
    net: -3,
  ),
  const CommandRejectedEvent(reason: 'presentation_fixture_rejection'),
  AllPlayersSubmittedEvent(turn: 6, playerIds: const ['player_1', 'player_2']),
  const PlayerTimedOutEvent(turn: 6, playerId: 'player_2'),
  const TurnAutoResolvedEvent(
    turn: 6,
    playerId: 'player_2',
    unitOrderCount: 2,
    cityProductionCount: 1,
    researchSelected: true,
  ),
  const PlayerKickedEvent(
    turn: 6,
    playerId: 'player_2',
    reason: 'turn_timeout',
    timeoutStreak: 3,
  ),
  const CivilizationMetEvent(playerId: 'player_1', metPlayerId: 'player_2'),
  const TurnEndedEvent(playerId: 'player_1'),
  const WorkerCompletedJobEvent(unitId: 'worker_1'),
  const DominationThresholdReachedEvent(
    playerId: 'player_1',
    controlPercent: 62.5,
    requiredControlPercent: 60,
    holdTurns: 2,
    requiredHoldTurns: 3,
  ),
  const UnitMovedEvent(
    unitId: 'attacker_1',
    fromCol: 0,
    fromRow: 0,
    toCol: 1,
    toRow: 0,
  ),
  FortifiedUnitThreatenedEvent(
    unitId: 'attacker_1',
    ownerPlayerId: 'player_1',
    targets: const [
      FortifiedUnitThreatTarget(unitId: 'defender_1', col: 2, row: 0),
    ],
  ),
  const UnitGainedExperienceEvent(
    unitId: 'attacker_1',
    ownerPlayerId: 'player_1',
    amount: 3,
    totalExperience: 7,
    rank: UnitVeterancyRank.veteran,
    promoted: true,
  ),
];

final _combatOutcome = CombatOutcome(
  attackerUnitId: 'attacker_1',
  defenderUnitId: 'defender_1',
  attackerHpAfter: 8,
  defenderHpAfter: 2,
  attackerKilled: false,
  defenderKilled: false,
  defenderRetreated: true,
  steps: [AttackStep(damage: 4), RetaliationStep(damage: 2)],
);
