import 'package:aonw_core/ai/ai_persona.dart';
import 'package:aonw_core/ai/civilization/civilization_profile.dart';
import 'package:aonw_core/ai/civilization/persona_weights.dart';
import 'package:aonw_core/ai/civilization/tech_branch_preferences.dart';
import 'package:aonw_core/game/domain/player.dart';

abstract final class CivilizationProfiles {
  static const poland = CivilizationProfile(
    country: PlayerCountry.poland,
    displayName: 'Poland',
    defaultPersona: AiPersona.balanced,
    civBias: PersonaWeights(
      aggression: 1.00,
      expansion: 1.00,
      economy: 1.00,
      science: 1.00,
    ),
    belligerence: 1.00,
    expansionDistance: 1.00,
    frontierTolerance: 1.00,
    techBias: TechBranchPreferences.identity,
  );

  static const all = <PlayerCountry, CivilizationProfile>{
    PlayerCountry.poland: poland,
    PlayerCountry.ukraine: CivilizationProfile(
      country: PlayerCountry.ukraine,
      displayName: 'Ukraine',
      defaultPersona: AiPersona.expansive,
      civBias: PersonaWeights(
        aggression: 1.00,
        expansion: 1.12,
        economy: 1.05,
        science: 1.05,
      ),
      belligerence: 1.00,
      expansionDistance: 1.12,
      frontierTolerance: 1.15,
      techBias: TechBranchPreferences(
        weights: {TechBranch.expansion: 1.10, TechBranch.economy: 1.05},
      ),
    ),
    PlayerCountry.germany: CivilizationProfile(
      country: PlayerCountry.germany,
      displayName: 'Germany',
      defaultPersona: AiPersona.aggressive,
      civBias: PersonaWeights(
        aggression: 1.10,
        expansion: 1.00,
        economy: 1.15,
        science: 1.00,
      ),
      belligerence: 1.25,
      expansionDistance: 0.95,
      frontierTolerance: 1.10,
      techBias: TechBranchPreferences(
        weights: {TechBranch.military: 1.15, TechBranch.economy: 1.05},
      ),
    ),
    PlayerCountry.france: CivilizationProfile(
      country: PlayerCountry.france,
      displayName: 'France',
      defaultPersona: AiPersona.scientific,
      civBias: PersonaWeights(
        aggression: 0.95,
        expansion: 1.12,
        economy: 1.00,
        science: 1.10,
      ),
      belligerence: 0.95,
      expansionDistance: 1.08,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences(
        weights: {TechBranch.science: 1.10, TechBranch.expansion: 1.05},
      ),
    ),
    PlayerCountry.unitedKingdom: CivilizationProfile(
      country: PlayerCountry.unitedKingdom,
      displayName: 'United Kingdom',
      defaultPersona: AiPersona.economic,
      civBias: PersonaWeights(
        aggression: 1.00,
        expansion: 1.00,
        economy: 1.15,
        science: 1.10,
      ),
      belligerence: 1.00,
      expansionDistance: 1.15,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences(weights: {TechBranch.economy: 1.15}),
    ),
    PlayerCountry.italy: CivilizationProfile(
      country: PlayerCountry.italy,
      displayName: 'Italy',
      defaultPersona: AiPersona.economic,
      civBias: PersonaWeights(
        aggression: 0.95,
        expansion: 0.95,
        economy: 1.15,
        science: 1.00,
      ),
      belligerence: 0.95,
      expansionDistance: 0.95,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences(weights: {TechBranch.economy: 1.10}),
    ),
    PlayerCountry.spain: CivilizationProfile(
      country: PlayerCountry.spain,
      displayName: 'Spain',
      defaultPersona: AiPersona.expansive,
      civBias: PersonaWeights(
        aggression: 1.10,
        expansion: 1.15,
        economy: 1.00,
        science: 1.00,
      ),
      belligerence: 1.15,
      expansionDistance: 1.25,
      frontierTolerance: 1.15,
      techBias: TechBranchPreferences(weights: {TechBranch.expansion: 1.15}),
    ),
    PlayerCountry.netherlands: CivilizationProfile(
      country: PlayerCountry.netherlands,
      displayName: 'Netherlands',
      defaultPersona: AiPersona.economic,
      civBias: PersonaWeights(
        aggression: 0.90,
        expansion: 1.00,
        economy: 1.20,
        science: 1.05,
      ),
      belligerence: 0.90,
      expansionDistance: 1.00,
      frontierTolerance: 0.95,
      techBias: TechBranchPreferences(weights: {TechBranch.economy: 1.20}),
    ),
    PlayerCountry.sweden: CivilizationProfile(
      country: PlayerCountry.sweden,
      displayName: 'Sweden',
      defaultPersona: AiPersona.scientific,
      civBias: PersonaWeights(
        aggression: 1.00,
        expansion: 1.00,
        economy: 1.10,
        science: 1.15,
      ),
      belligerence: 1.00,
      expansionDistance: 1.00,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences(weights: {TechBranch.science: 1.15}),
    ),
    PlayerCountry.russia: CivilizationProfile(
      country: PlayerCountry.russia,
      displayName: 'Russia',
      defaultPersona: AiPersona.expansive,
      civBias: PersonaWeights(
        aggression: 1.00,
        expansion: 1.20,
        economy: 1.05,
        science: 1.10,
      ),
      belligerence: 1.05,
      expansionDistance: 1.25,
      frontierTolerance: 1.20,
      techBias: TechBranchPreferences(
        weights: {TechBranch.expansion: 1.15, TechBranch.science: 1.05},
      ),
    ),
    PlayerCountry.unitedStates: CivilizationProfile(
      country: PlayerCountry.unitedStates,
      displayName: 'United States',
      defaultPersona: AiPersona.expansive,
      civBias: PersonaWeights(
        aggression: 1.10,
        expansion: 1.15,
        economy: 1.10,
        science: 1.00,
      ),
      belligerence: 1.10,
      expansionDistance: 1.20,
      frontierTolerance: 1.10,
      techBias: TechBranchPreferences(weights: {TechBranch.expansion: 1.10}),
    ),
    PlayerCountry.canada: CivilizationProfile(
      country: PlayerCountry.canada,
      displayName: 'Canada',
      defaultPersona: AiPersona.economic,
      civBias: PersonaWeights(
        aggression: 0.85,
        expansion: 1.10,
        economy: 1.10,
        science: 1.00,
      ),
      belligerence: 0.85,
      expansionDistance: 1.15,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences.identity,
    ),
    PlayerCountry.china: CivilizationProfile(
      country: PlayerCountry.china,
      displayName: 'China',
      defaultPersona: AiPersona.balanced,
      civBias: PersonaWeights(
        aggression: 1.05,
        expansion: 1.05,
        economy: 1.15,
        science: 1.10,
      ),
      belligerence: 1.05,
      expansionDistance: 1.05,
      frontierTolerance: 1.05,
      techBias: TechBranchPreferences(weights: {TechBranch.economy: 1.10}),
    ),
    PlayerCountry.korea: CivilizationProfile(
      country: PlayerCountry.korea,
      displayName: 'Korea',
      defaultPersona: AiPersona.scientific,
      civBias: PersonaWeights(
        aggression: 0.95,
        expansion: 0.95,
        economy: 1.00,
        science: 1.20,
      ),
      belligerence: 0.95,
      expansionDistance: 0.95,
      frontierTolerance: 1.00,
      techBias: TechBranchPreferences(weights: {TechBranch.science: 1.20}),
    ),
    PlayerCountry.japan: CivilizationProfile(
      country: PlayerCountry.japan,
      displayName: 'Japan',
      defaultPersona: AiPersona.aggressive,
      civBias: PersonaWeights(
        aggression: 1.15,
        expansion: 0.95,
        economy: 1.00,
        science: 1.10,
      ),
      belligerence: 1.20,
      expansionDistance: 0.90,
      frontierTolerance: 0.95,
      techBias: TechBranchPreferences(
        weights: {TechBranch.military: 1.10, TechBranch.science: 1.05},
      ),
    ),
    PlayerCountry.portugal: CivilizationProfile(
      country: PlayerCountry.portugal,
      displayName: 'Portugal',
      defaultPersona: AiPersona.economic,
      civBias: PersonaWeights(
        aggression: 0.90,
        expansion: 1.15,
        economy: 1.20,
        science: 1.05,
      ),
      belligerence: 0.90,
      expansionDistance: 1.20,
      frontierTolerance: 1.10,
      techBias: TechBranchPreferences(
        weights: {TechBranch.economy: 1.15, TechBranch.expansion: 1.10},
      ),
    ),
  };
}
