enum CityBuildingType {
  granary,
  waterMill,
  workshop,
  storehouse,
  housing,
  merchantHall,
  stonemason,
  barracks,
  marketplace,
  port,
  aqueduct,
  forge,
  stable,
  bank,
  buildersGuild,
  factory,
  lighthouse,
  trainingGrounds,
  townHall,
  monument,
  archive,
  academy,
  university,
  observatory,
  laboratory,
  reactor,
  courthouse,
  court,
  governorsOffice,
  surveyorsOffice,
  planningOffice,
  apothecary,
  publicBaths,
  hospital,
  ministries,
  walls,
  armory,
  siegeWorkshop,
  citadel,
  warCollege,
  conscriptionOffice,
  borderFort,
  airfield,
  artisansGuild,
  masterWorkshop,
  steelworks,
  railDepot,
  powerPlant,
  assemblyPlant,
  refinery,
  mapRoom,
  shipyard,
  dryDock,
  navalAcademy,
  harborCustoms,
  museum,
  parliament,
  broadcastTower,
  worldFairGrounds;

  String get displayName => switch (this) {
    CityBuildingType.granary => 'Granary',
    CityBuildingType.waterMill => 'Water mill',
    CityBuildingType.workshop => 'Workshop',
    CityBuildingType.storehouse => 'Storehouse',
    CityBuildingType.housing => 'Housing',
    CityBuildingType.merchantHall => 'Merchant hall',
    CityBuildingType.stonemason => 'Stonemason',
    CityBuildingType.barracks => 'Barracks',
    CityBuildingType.marketplace => 'Marketplace',
    CityBuildingType.port => 'Port',
    CityBuildingType.aqueduct => 'Aqueduct',
    CityBuildingType.forge => 'Forge',
    CityBuildingType.stable => 'Stable',
    CityBuildingType.bank => 'Bank',
    CityBuildingType.buildersGuild => 'Builders guild',
    CityBuildingType.factory => 'Factory',
    CityBuildingType.lighthouse => 'Lighthouse',
    CityBuildingType.trainingGrounds => 'Training grounds',
    CityBuildingType.townHall => 'Town hall',
    CityBuildingType.monument => 'Monument',
    CityBuildingType.archive => 'Archive',
    CityBuildingType.academy => 'Academy',
    CityBuildingType.university => 'University',
    CityBuildingType.observatory => 'Observatory',
    CityBuildingType.laboratory => 'Laboratory',
    CityBuildingType.reactor => 'Reactor',
    CityBuildingType.courthouse => 'Courthouse',
    CityBuildingType.court => 'Court',
    CityBuildingType.governorsOffice => 'Governor office',
    CityBuildingType.surveyorsOffice => 'Surveyor office',
    CityBuildingType.planningOffice => 'Planning office',
    CityBuildingType.apothecary => 'Apothecary',
    CityBuildingType.publicBaths => 'Public baths',
    CityBuildingType.hospital => 'Hospital',
    CityBuildingType.ministries => 'Ministries',
    CityBuildingType.walls => 'Walls',
    CityBuildingType.armory => 'Armory',
    CityBuildingType.siegeWorkshop => 'Siege workshop',
    CityBuildingType.citadel => 'Citadel',
    CityBuildingType.warCollege => 'War college',
    CityBuildingType.conscriptionOffice => 'Conscription office',
    CityBuildingType.borderFort => 'Border fort',
    CityBuildingType.airfield => 'Airfield',
    CityBuildingType.artisansGuild => 'Artisans guild',
    CityBuildingType.masterWorkshop => 'Master workshop',
    CityBuildingType.steelworks => 'Steelworks',
    CityBuildingType.railDepot => 'Rail depot',
    CityBuildingType.powerPlant => 'Power plant',
    CityBuildingType.assemblyPlant => 'Assembly plant',
    CityBuildingType.refinery => 'Refinery',
    CityBuildingType.mapRoom => 'Map room',
    CityBuildingType.shipyard => 'Shipyard',
    CityBuildingType.dryDock => 'Dry dock',
    CityBuildingType.navalAcademy => 'Naval academy',
    CityBuildingType.harborCustoms => 'Harbor customs',
    CityBuildingType.museum => 'Museum',
    CityBuildingType.parliament => 'Parliament',
    CityBuildingType.broadcastTower => 'Broadcast tower',
    CityBuildingType.worldFairGrounds => 'World fair grounds',
  };

  static CityBuildingType fromString(String value) {
    return CityBuildingType.values.firstWhere(
      (type) => type.name == value,
      orElse: () => throw ArgumentError('Unknown city building type: $value'),
    );
  }
}
