import 'package:aonw_core/game/domain/player.dart';

abstract final class CityNameCatalog {
  static String nextName({
    required PlayerCountry country,
    required int sequence,
  }) {
    final names = _names[country] ?? _names[PlayerCountry.poland]!;
    if (sequence <= 0) return names.first;
    final index = sequence - 1;
    final baseName = names[index % names.length];
    final cycle = index ~/ names.length;
    return cycle == 0 ? baseName : '$baseName ${cycle + 1}';
  }

  static const Map<PlayerCountry, List<String>> _names = {
    PlayerCountry.poland: [
      'Warszawa',
      'Krakow',
      'Gdansk',
      'Wroclaw',
      'Poznan',
      'Lublin',
      'Katowice',
      'Torun',
      'Poniatowa',
    ],
    PlayerCountry.ukraine: [
      'Kyiv',
      'Lviv',
      'Odesa',
      'Kharkiv',
      'Dnipro',
      'Zaporizhzhia',
      'Donetsk',
      'Krym',
    ],
    PlayerCountry.germany: [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Dresden',
      'Bremen',
      'Leipzig',
    ],
    PlayerCountry.france: [
      'Paris',
      'Lyon',
      'Marseille',
      'Bordeaux',
      'Toulouse',
      'Nantes',
      'Strasbourg',
      'Lille',
    ],
    PlayerCountry.unitedKingdom: [
      'London',
      'Edinburgh',
      'Cardiff',
      'Belfast',
      'Manchester',
      'Liverpool',
      'York',
      'Bristol',
    ],
    PlayerCountry.italy: [
      'Rome',
      'Milan',
      'Venice',
      'Florence',
      'Naples',
      'Turin',
      'Genoa',
      'Bologna',
    ],
    PlayerCountry.spain: [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Seville',
      'Granada',
      'Bilbao',
      'Zaragoza',
      'Toledo',
    ],
    PlayerCountry.netherlands: [
      'Amsterdam',
      'Rotterdam',
      'Utrecht',
      'The Hague',
      'Eindhoven',
      'Groningen',
      'Haarlem',
      'Leiden',
    ],
    PlayerCountry.sweden: [
      'Stockholm',
      'Gothenburg',
      'Malmo',
      'Uppsala',
      'Lund',
      'Umea',
      'Vasteras',
      'Orebro',
    ],
    PlayerCountry.russia: [
      'Moscow',
      'Saint Petersburg',
      'Novgorod',
      'Kazan',
      'Smolensk',
      'Yaroslavl',
      'Vladimir',
      'Tver',
    ],
    PlayerCountry.unitedStates: [
      'Washington',
      'New York',
      'Boston',
      'Philadelphia',
      'Chicago',
      'San Francisco',
      'Atlanta',
      'Seattle',
    ],
    PlayerCountry.canada: [
      'Ottawa',
      'Toronto',
      'Montreal',
      'Vancouver',
      'Quebec City',
      'Calgary',
      'Halifax',
      'Winnipeg',
    ],
    PlayerCountry.china: [
      'Beijing',
      'Shanghai',
      'Nanjing',
      'Guangzhou',
      'Chengdu',
      "Xi'an",
      'Hangzhou',
      'Wuhan',
    ],
    PlayerCountry.korea: [
      'Seoul',
      'Busan',
      'Incheon',
      'Daegu',
      'Daejeon',
      'Gwangju',
      'Suwon',
      'Jeonju',
    ],
    PlayerCountry.japan: [
      'Tokyo',
      'Kyoto',
      'Osaka',
      'Nara',
      'Yokohama',
      'Nagoya',
      'Hiroshima',
      'Sapporo',
    ],
    PlayerCountry.portugal: [
      'Lisbon',
      'Porto',
      'Coimbra',
      'Braga',
      'Faro',
      'Evora',
      'Guimaraes',
      'Aveiro',
    ],
  };
}
