use aonw_contracts::ReplayCommandDto;

pub(crate) const fn command_name(command: &ReplayCommandDto) -> &'static str {
    match command {
        ReplayCommandDto::DeclareWar { .. } => "DeclareWar",
        ReplayCommandDto::SendGoldGift { .. } => "SendGoldGift",
        ReplayCommandDto::OpenResourceTrade { .. } => "OpenResourceTrade",
        ReplayCommandDto::OpenResourceExchange { .. } => "OpenResourceExchange",
        ReplayCommandDto::SelectTechnology { .. } => "SelectTechnology",
        ReplayCommandDto::SendDiplomaticProposal { .. } => "SendDiplomaticProposal",
        ReplayCommandDto::RespondDiplomaticProposal { .. } => "RespondDiplomaticProposal",
        ReplayCommandDto::SendDiplomaticMessage { .. } => "SendDiplomaticMessage",
        ReplayCommandDto::RespondDiplomaticMessage { .. } => "RespondDiplomaticMessage",
        ReplayCommandDto::StartArtifactExcavation { .. } => "StartArtifactExcavation",
        ReplayCommandDto::StoreArtifactInCity { .. } => "StoreArtifactInCity",
        ReplayCommandDto::TradeArtifact { .. } => "TradeArtifact",
        ReplayCommandDto::FoundCity { .. } => "FoundCity",
        ReplayCommandDto::ToggleWorkedHex { .. } => "ToggleWorkedHex",
        ReplayCommandDto::SelectCityExpansionHex { .. } => "SelectCityExpansionHex",
        ReplayCommandDto::StartBuilding { .. } => "StartBuilding",
        ReplayCommandDto::StartUnitProduction { .. } => "StartUnitProduction",
        ReplayCommandDto::StartCityProject { .. } => "StartCityProject",
        ReplayCommandDto::StartWonder { .. } => "StartWonder",
        ReplayCommandDto::SetCitySpecialization { .. } => "SetCitySpecialization",
        ReplayCommandDto::RushProduction { .. } => "RushProduction",
        ReplayCommandDto::SelectWorkerImprovement { .. } => "SelectWorkerImprovement",
        ReplayCommandDto::ConfirmWorkerImprovement { .. } => "ConfirmWorkerImprovement",
        ReplayCommandDto::CancelWorkerJob { .. } => "CancelWorkerJob",
        ReplayCommandDto::AssignWorkerToHex { .. } => "AssignWorkerToHex",
        ReplayCommandDto::CancelWorkerAssignment { .. } => "CancelWorkerAssignment",
        ReplayCommandDto::BuildRoad { .. } => "BuildRoad",
        ReplayCommandDto::AutomateWorker { .. } => "AutomateWorker",
        ReplayCommandDto::AttackHex { .. } => "AttackHex",
        ReplayCommandDto::MoveUnit { .. } => "MoveUnit",
        ReplayCommandDto::AutoExploreUnit { .. } => "AutoExploreUnit",
        ReplayCommandDto::AssignMerchantTradeRoute { .. } => "AssignMerchantTradeRoute",
        ReplayCommandDto::MoveMerchantToCity { .. } => "MoveMerchantToCity",
        ReplayCommandDto::DetachTroop { .. } => "DetachTroop",
        ReplayCommandDto::CancelUnitAction { .. } => "CancelUnitAction",
        ReplayCommandDto::SkipUnitTurn { .. } => "SkipUnitTurn",
        ReplayCommandDto::FortifyUnit { .. } => "FortifyUnit",
        ReplayCommandDto::EndTurn { .. } => "EndTurn",
        ReplayCommandDto::SubmitTurn { .. } => "SubmitTurn",
    }
}
