include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - build/**
    - lib/src/generated/**
    - test/integration/test_tools/serverpod_test_tools.dart
