include:
  - package:lints/recommended.yaml
  - ../analysis_options_base.yaml

analyzer:
  exclude:
    - build/**
    - lib/src/generated/**
    - test/integration/test_tools/serverpod_test_tools.dart
