part of 'technology_catalog.dart';

const _foundationToNavigationTechnologies = <TechnologyId, TechnologyDefinition>{
  TechnologyId.agriculture: TechnologyDefinition(
    id: TechnologyId.agriculture,
    name: 'Agriculture',
    description:
        'Unlocks reliable food improvements and fruit orchards for early growth.',
    era: TechnologyEra.foundation,
    baseCost: 6,
    unlocks: [
      UnlockFieldImprovement(FieldImprovementType.farm),
      UnlockFieldImprovement(FieldImprovementType.riverFarm),
      UnlockFieldImprovement(FieldImprovementType.orchard),
    ],
    boosts: [
      TechnologyBoostDefinition(
        condition: ControlsAnyResource({ResourceType.wheat, ResourceType.rice}),
        discount: 0.25,
        label: 'Wheat or rice',
      ),
    ],
    treePosition: TechnologyTreePosition(column: 0, row: 0),
  ),
  TechnologyId.woodworking: TechnologyDefinition(
    id: TechnologyId.woodworking,
    name: 'Woodworking',
    description: 'Turns forests into early production opportunities.',
    era: TechnologyEra.settlement,
    baseCost: 6,
    prerequisites: [TechnologyId.mining],
    unlocks: [UnlockFieldImprovement(FieldImprovementType.lumberMill)],
    treePosition: TechnologyTreePosition(column: 1, row: 4),
  ),
  TechnologyId.mining: TechnologyDefinition(
    id: TechnologyId.mining,
    name: 'Mining',
    description:
        'Unlocks mines, mineral prospecting, and starts the production branch.',
    era: TechnologyEra.foundation,
    baseCost: 6,
    unlocks: [
      UnlockFieldImprovement(FieldImprovementType.mine),
      UnlockFieldImprovement(FieldImprovementType.prospectorCamp),
    ],
    boosts: [
      TechnologyBoostDefinition(
        condition: ControlsAnyResource({
          ResourceType.iron,
          ResourceType.marble,
        }),
        discount: 0.25,
        label: 'Iron or marble',
      ),
    ],
    treePosition: TechnologyTreePosition(column: 0, row: 4),
  ),
  TechnologyId.animalHusbandry: TechnologyDefinition(
    id: TechnologyId.animalHusbandry,
    name: 'Animal Husbandry',
    description: 'Unlocks pasture improvements and the cavalry branch.',
    era: TechnologyEra.settlement,
    baseCost: 6,
    prerequisites: [TechnologyId.agriculture],
    unlocks: [UnlockFieldImprovement(FieldImprovementType.pasture)],
    treePosition: TechnologyTreePosition(column: 1, row: 0),
  ),
  TechnologyId.hunting: TechnologyDefinition(
    id: TechnologyId.hunting,
    name: 'Hunting',
    description: 'Unlocks camps for forest and wildlife resources.',
    era: TechnologyEra.foundation,
    baseCost: 7,
    unlocks: [
      UnlockFieldImprovement(FieldImprovementType.camp),
      UnlockUnitType(GameUnitType.archer),
    ],
    treePosition: TechnologyTreePosition(column: 0, row: 8),
  ),
  TechnologyId.fishing: TechnologyDefinition(
    id: TechnologyId.fishing,
    name: 'Fishing',
    description: 'Unlocks coastal food improvements.',
    era: TechnologyEra.settlement,
    baseCost: 6,
    prerequisites: [TechnologyId.hunting],
    unlocks: [UnlockFieldImprovement(FieldImprovementType.fishingBoats)],
    boosts: [
      TechnologyBoostDefinition(
        condition: ControlsResource(ResourceType.fish),
        discount: 0.25,
        label: 'Fish',
      ),
    ],
    treePosition: TechnologyTreePosition(column: 1, row: 9),
  ),
  TechnologyId.craftsmanship: TechnologyDefinition(
    id: TechnologyId.craftsmanship,
    name: 'Craftsmanship',
    description: 'Unlocks early urban production.',
    era: TechnologyEra.settlement,
    baseCost: 7,
    prerequisites: [TechnologyId.mining],
    unlocks: [UnlockCityBuilding(CityBuildingUnlockId.workshop)],
    treePosition: TechnologyTreePosition(column: 1, row: 5),
  ),
  TechnologyId.trade: TechnologyDefinition(
    id: TechnologyId.trade,
    name: 'Trade',
    description:
        'Unlocks the first gold-focused city building and field trade.',
    era: TechnologyEra.settlement,
    baseCost: 7,
    prerequisites: [TechnologyId.agriculture],
    unlocks: [
      UnlockCityBuilding(CityBuildingUnlockId.merchantHall),
      UnlockUnitType(GameUnitType.merchant),
      UnlockFieldImprovement(FieldImprovementType.vineyard),
      UnlockFieldImprovement(FieldImprovementType.tradingPost),
    ],
    treePosition: TechnologyTreePosition(column: 1, row: 1),
  ),
  TechnologyId.storage: TechnologyDefinition(
    id: TechnologyId.storage,
    name: 'Storage',
    description: 'Improves food retention and city stability.',
    era: TechnologyEra.expansion,
    baseCost: 11,
    prerequisites: [TechnologyId.agriculture],
    unlocks: [UnlockCityBuilding(CityBuildingUnlockId.storehouse)],
    boosts: [
      TechnologyBoostDefinition(
        condition: HasImprovementCount(
          improvementType: FieldImprovementType.farm,
          count: 2,
        ),
        discount: 0.25,
        label: '2 farms',
      ),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 0),
  ),
  TechnologyId.waterEngineering: TechnologyDefinition(
    id: TechnologyId.waterEngineering,
    name: 'Water Engineering',
    description: 'Adds river-based growth and production options.',
    era: TechnologyEra.expansion,
    baseCost: 12,
    prerequisites: [TechnologyId.agriculture],
    unlocks: [
      UnlockCityBuilding(CityBuildingUnlockId.waterMill),
      UnlockWonder(WonderType.hangingGardens),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 1),
  ),
  TechnologyId.stoneworking: TechnologyDefinition(
    id: TechnologyId.stoneworking,
    name: 'Stoneworking',
    description: 'Unlocks quarrying and stone city development.',
    era: TechnologyEra.expansion,
    baseCost: 13,
    prerequisites: [TechnologyId.mining],
    unlocks: [
      UnlockFieldImprovement(FieldImprovementType.quarry),
      UnlockCityBuilding(CityBuildingUnlockId.stonemason),
      UnlockWonder(WonderType.petra),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 4),
  ),
  TechnologyId.militaryOrganization: TechnologyDefinition(
    id: TechnologyId.militaryOrganization,
    name: 'Military Organization',
    description: 'Unlocks the first military city infrastructure and drills.',
    era: TechnologyEra.expansion,
    baseCost: 13,
    prerequisites: [TechnologyId.hunting],
    unlocks: [
      UnlockCityBuilding(CityBuildingUnlockId.barracks),
      UnlockCityBuilding(CityBuildingUnlockId.armory),
      UnlockUnitType(GameUnitType.spearman),
      UnlockWonder(WonderType.greatWall),
    ],
    effects: [ArmyCombatStatsBonus(hp: 1)],
    treePosition: TechnologyTreePosition(column: 2, row: 8),
  ),
  TechnologyId.advancedTrade: TechnologyDefinition(
    id: TechnologyId.advancedTrade,
    name: 'Advanced Trade',
    description: 'Unlocks stronger gold and science economy.',
    era: TechnologyEra.expansion,
    baseCost: 14,
    prerequisites: [TechnologyId.trade],
    unlocks: [
      UnlockCityBuilding(CityBuildingUnlockId.marketplace),
      UnlockFieldImprovement(FieldImprovementType.plantation),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 2),
  ),
  TechnologyId.construction: TechnologyDefinition(
    id: TechnologyId.construction,
    name: 'Construction',
    description: 'Unlocks housing and a path toward administration.',
    era: TechnologyEra.expansion,
    baseCost: 13,
    prerequisites: [TechnologyId.craftsmanship],
    unlocks: [UnlockCityBuilding(CityBuildingUnlockId.housing)],
    boosts: [
      TechnologyBoostDefinition(
        condition: HasAnyImprovement(FieldImprovementType.mine),
        discount: 0.25,
        label: 'Mine',
      ),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 5),
  ),
  TechnologyId.navigation: TechnologyDefinition(
    id: TechnologyId.navigation,
    name: 'Navigation',
    description: 'Unlocks coastal city infrastructure and pearl diving.',
    era: TechnologyEra.expansion,
    baseCost: 12,
    prerequisites: [TechnologyId.fishing],
    unlocks: [
      UnlockCityBuilding(CityBuildingUnlockId.port),
      UnlockFieldImprovement(FieldImprovementType.pearlDivers),
    ],
    treePosition: TechnologyTreePosition(column: 2, row: 9),
  ),
};
