part of 'technology_catalog.dart';

const _irrigationToBureaucracyTechnologies =
    <TechnologyId, TechnologyDefinition>{
      TechnologyId.irrigation: TechnologyDefinition(
        id: TechnologyId.irrigation,
        name: 'Irrigation',
        description: 'Turns water control into a mature growth branch.',
        era: TechnologyEra.specialization,
        baseCost: 18,
        prerequisites: [TechnologyId.waterEngineering],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.aqueduct)],
        treePosition: TechnologyTreePosition(column: 3, row: 0),
      ),
      TechnologyId.banking: TechnologyDefinition(
        id: TechnologyId.banking,
        name: 'Banking',
        description: 'Turns market trade into stored city wealth.',
        era: TechnologyEra.specialization,
        baseCost: 19,
        prerequisites: [TechnologyId.advancedTrade],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.bank),
          UnlockWonder(WonderType.centralBank),
        ],
        treePosition: TechnologyTreePosition(column: 3, row: 2),
      ),
      TechnologyId.engineering: TechnologyDefinition(
        id: TechnologyId.engineering,
        name: 'Engineering',
        description: 'Specializes construction into stronger infrastructure.',
        era: TechnologyEra.specialization,
        baseCost: 19,
        prerequisites: [TechnologyId.construction],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.buildersGuild)],
        treePosition: TechnologyTreePosition(column: 3, row: 5),
      ),
      TechnologyId.metallurgy: TechnologyDefinition(
        id: TechnologyId.metallurgy,
        name: 'Metallurgy',
        description: 'Unlocks forge infrastructure and metal production.',
        era: TechnologyEra.specialization,
        baseCost: 20,
        prerequisites: [TechnologyId.stoneworking],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.forge)],
        treePosition: TechnologyTreePosition(column: 3, row: 4),
      ),
      TechnologyId.horsebackRiding: TechnologyDefinition(
        id: TechnologyId.horsebackRiding,
        name: 'Horseback Riding',
        description:
            'Unlocks stable infrastructure, horse ranches, and cavalry growth.',
        era: TechnologyEra.specialization,
        baseCost: 18,
        prerequisites: [TechnologyId.animalHusbandry, TechnologyId.hunting],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.stable),
          UnlockFieldImprovement(FieldImprovementType.horseRanch),
          UnlockUnitType(GameUnitType.cavalry),
        ],
        boosts: [
          TechnologyBoostDefinition(
            condition: ControlsResource(ResourceType.horses),
            discount: 0.25,
            label: 'Horses',
          ),
        ],
        treePosition: TechnologyTreePosition(column: 3, row: 8),
      ),
      TechnologyId.shipbuilding: TechnologyDefinition(
        id: TechnologyId.shipbuilding,
        name: 'Shipbuilding',
        description: 'Extends exploration into coastal city development.',
        era: TechnologyEra.specialization,
        baseCost: 18,
        prerequisites: [TechnologyId.navigation],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.lighthouse)],
        treePosition: TechnologyTreePosition(column: 3, row: 10),
      ),
      TechnologyId.writing: TechnologyDefinition(
        id: TechnologyId.writing,
        name: 'Writing',
        description: 'Starts formal knowledge, law, and administration.',
        era: TechnologyEra.settlement,
        baseCost: 8,
        prerequisites: [TechnologyId.agriculture],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.archive),
          UnlockWonder(WonderType.greatLibrary),
        ],
        treePosition: TechnologyTreePosition(column: 1, row: 2),
      ),
      TechnologyId.mathematics: TechnologyDefinition(
        id: TechnologyId.mathematics,
        name: 'Mathematics',
        description:
            'Connects science with territory planning and infrastructure.',
        era: TechnologyEra.expansion,
        baseCost: 15,
        prerequisites: [TechnologyId.writing, TechnologyId.construction],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.surveyorsOffice)],
        treePosition: TechnologyTreePosition(column: 2, row: 3),
      ),
      TechnologyId.medicine: TechnologyDefinition(
        id: TechnologyId.medicine,
        name: 'Medicine',
        description: 'Improves health and long-term growth in larger cities.',
        era: TechnologyEra.expansion,
        baseCost: 16,
        prerequisites: [TechnologyId.writing, TechnologyId.storage],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.apothecary),
          UnlockCityBuilding(CityBuildingUnlockId.publicBaths),
          UnlockCityBuilding(CityBuildingUnlockId.hospital),
        ],
        treePosition: TechnologyTreePosition(column: 2, row: 6),
      ),
      TechnologyId.civilService: TechnologyDefinition(
        id: TechnologyId.civilService,
        name: 'Civil Service',
        description: 'Makes large empires easier to govern and stabilize.',
        era: TechnologyEra.specialization,
        baseCost: 22,
        prerequisites: [TechnologyId.administration],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.courthouse)],
        treePosition: TechnologyTreePosition(column: 4, row: 1),
      ),
      TechnologyId.siegecraft: TechnologyDefinition(
        id: TechnologyId.siegecraft,
        name: 'Siegecraft',
        description: 'Unlocks siege pressure against fortified cities.',
        era: TechnologyEra.specialization,
        baseCost: 22,
        prerequisites: [
          TechnologyId.militaryOrganization,
          TechnologyId.engineering,
        ],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.siegeWorkshop),
          UnlockUnitType(GameUnitType.catapult),
        ],
        treePosition: TechnologyTreePosition(column: 4, row: 10),
      ),
      TechnologyId.cartography: TechnologyDefinition(
        id: TechnologyId.cartography,
        name: 'Cartography',
        description: 'Improves exploration, maps, and coastal reach.',
        era: TechnologyEra.specialization,
        baseCost: 20,
        prerequisites: [TechnologyId.navigation],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.mapRoom),
          UnlockUnitType(GameUnitType.scoutShip),
        ],
        treePosition: TechnologyTreePosition(column: 3, row: 11),
      ),
      TechnologyId.guilds: TechnologyDefinition(
        id: TechnologyId.guilds,
        name: 'Guilds',
        description: 'Adds a production stage between workshop and industry.',
        era: TechnologyEra.specialization,
        baseCost: 21,
        prerequisites: [TechnologyId.craftsmanship, TechnologyId.trade],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.artisansGuild),
          UnlockCityBuilding(CityBuildingUnlockId.masterWorkshop),
        ],
        treePosition: TechnologyTreePosition(column: 3, row: 6),
      ),
      TechnologyId.law: TechnologyDefinition(
        id: TechnologyId.law,
        name: 'Law',
        description: 'Adds order, policy, and civic control to cities.',
        era: TechnologyEra.specialization,
        baseCost: 22,
        prerequisites: [TechnologyId.writing, TechnologyId.administration],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.court),
          UnlockWonder(WonderType.grandCathedral),
        ],
        treePosition: TechnologyTreePosition(column: 4, row: 3),
      ),
      TechnologyId.education: TechnologyDefinition(
        id: TechnologyId.education,
        name: 'Education',
        description: 'Builds the full science path for developed cities.',
        era: TechnologyEra.specialization,
        baseCost: 24,
        prerequisites: [TechnologyId.writing, TechnologyId.mathematics],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.academy),
          UnlockCityBuilding(CityBuildingUnlockId.university),
          UnlockWonder(WonderType.imperialUniversity),
        ],
        treePosition: TechnologyTreePosition(column: 4, row: 0),
      ),
      TechnologyId.ironWorking: TechnologyDefinition(
        id: TechnologyId.ironWorking,
        name: 'Iron Working',
        description: 'Improves production from controlled iron.',
        era: TechnologyEra.industry,
        baseCost: 20,
        prerequisites: [TechnologyId.metallurgy],
        effects: [
          StrategicResourceProductionBonus(
            resourceType: ResourceType.iron,
            production: 1,
          ),
        ],
        treePosition: TechnologyTreePosition(column: 4, row: 4),
      ),
      TechnologyId.coalMining: TechnologyDefinition(
        id: TechnologyId.coalMining,
        name: 'Coal Mining',
        description:
            'Improves production from controlled coal and unlocks coal shafts.',
        era: TechnologyEra.industry,
        baseCost: 20,
        prerequisites: [TechnologyId.metallurgy],
        unlocks: [UnlockFieldImprovement(FieldImprovementType.coalShaft)],
        effects: [
          StrategicResourceProductionBonus(
            resourceType: ResourceType.coal,
            production: 1,
          ),
        ],
        treePosition: TechnologyTreePosition(column: 4, row: 5),
      ),
      TechnologyId.machinery: TechnologyDefinition(
        id: TechnologyId.machinery,
        name: 'Machinery',
        description: 'Converts engineering knowledge into heavy production.',
        era: TechnologyEra.industry,
        baseCost: 23,
        prerequisites: [TechnologyId.engineering],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.factory)],
        treePosition: TechnologyTreePosition(column: 4, row: 6),
      ),
      TechnologyId.urbanPlanning: TechnologyDefinition(
        id: TechnologyId.urbanPlanning,
        name: 'Urban Planning',
        description: 'Develops large cities and more deliberate borders.',
        era: TechnologyEra.industry,
        baseCost: 28,
        prerequisites: [TechnologyId.engineering, TechnologyId.civilService],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.planningOffice)],
        treePosition: TechnologyTreePosition(column: 5, row: 5),
      ),
      TechnologyId.navalDoctrine: TechnologyDefinition(
        id: TechnologyId.navalDoctrine,
        name: 'Naval Doctrine',
        description: 'Turns ports into centers of fleet projection.',
        era: TechnologyEra.industry,
        baseCost: 28,
        prerequisites: [TechnologyId.shipbuilding, TechnologyId.cartography],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.shipyard),
          UnlockCityBuilding(CityBuildingUnlockId.dryDock),
          UnlockCityBuilding(CityBuildingUnlockId.navalAcademy),
          UnlockCityBuilding(CityBuildingUnlockId.harborCustoms),
          UnlockUnitType(GameUnitType.warship),
        ],
        treePosition: TechnologyTreePosition(column: 5, row: 11),
      ),
      TechnologyId.steel: TechnologyDefinition(
        id: TechnologyId.steel,
        name: 'Steel',
        description:
            'Introduces heavy industry and stronger front-line troops.',
        era: TechnologyEra.industry,
        baseCost: 30,
        prerequisites: [TechnologyId.ironWorking, TechnologyId.coalMining],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.steelworks),
          UnlockUnitType(GameUnitType.heavyInfantry),
        ],
        treePosition: TechnologyTreePosition(column: 5, row: 4),
      ),
      TechnologyId.bureaucracy: TechnologyDefinition(
        id: TechnologyId.bureaucracy,
        name: 'Bureaucracy',
        description: 'Adds a large civic goal after administration.',
        era: TechnologyEra.industry,
        baseCost: 30,
        prerequisites: [TechnologyId.civilService, TechnologyId.economy],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.governorsOffice),
          UnlockCityBuilding(CityBuildingUnlockId.ministries),
          UnlockCityBuilding(CityBuildingUnlockId.museum),
          UnlockCityBuilding(CityBuildingUnlockId.parliament),
        ],
        treePosition: TechnologyTreePosition(column: 5, row: 1),
      ),
    };
