part of 'technology_catalog.dart';

const _nationalismToNuclearPhysicsTechnologies =
    <TechnologyId, TechnologyDefinition>{
      TechnologyId.nationalism: TechnologyDefinition(
        id: TechnologyId.nationalism,
        name: 'Nationalism',
        description: 'Links border defense, mobilization, and empire identity.',
        era: TechnologyEra.strategy,
        baseCost: 32,
        prerequisites: [TechnologyId.fortifications, TechnologyId.tactics],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.conscriptionOffice),
          UnlockCityBuilding(CityBuildingUnlockId.borderFort),
          UnlockCityBuilding(CityBuildingUnlockId.citadel),
        ],
        treePosition: TechnologyTreePosition(column: 5, row: 8),
      ),
      TechnologyId.administration: TechnologyDefinition(
        id: TechnologyId.administration,
        name: 'Administration',
        description: 'Unlocks civic buildings for mature cities.',
        era: TechnologyEra.specialization,
        baseCost: 20,
        prerequisites: [TechnologyId.construction, TechnologyId.advancedTrade],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.townHall),
          UnlockCityBuilding(CityBuildingUnlockId.monument),
        ],
        treePosition: TechnologyTreePosition(column: 3, row: 1),
      ),
      TechnologyId.logistics: TechnologyDefinition(
        id: TechnologyId.logistics,
        name: 'Logistics',
        description: 'Improves army production throughput.',
        era: TechnologyEra.specialization,
        baseCost: 19,
        prerequisites: [TechnologyId.militaryOrganization],
        effects: [ArmyProductionMultiplier(0.15)],
        treePosition: TechnologyTreePosition(column: 3, row: 9),
      ),
      TechnologyId.tactics: TechnologyDefinition(
        id: TechnologyId.tactics,
        name: 'Tactics',
        description: 'Turns logistics into better battlefield coordination.',
        era: TechnologyEra.industry,
        baseCost: 23,
        prerequisites: [TechnologyId.logistics],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.trainingGrounds)],
        effects: [ArmyCombatStatsBonus(attack: 1, defense: 1)],
        treePosition: TechnologyTreePosition(column: 4, row: 9),
      ),
      TechnologyId.economy: TechnologyDefinition(
        id: TechnologyId.economy,
        name: 'Economy',
        description: 'Improves global gold output.',
        era: TechnologyEra.industry,
        baseCost: 26,
        prerequisites: [TechnologyId.banking],
        effects: [GlobalGoldMultiplier(0.10)],
        treePosition: TechnologyTreePosition(column: 4, row: 2),
      ),
      TechnologyId.urbanization: TechnologyDefinition(
        id: TechnologyId.urbanization,
        name: 'Urbanization',
        description: 'Raises the long-term city growth ceiling.',
        era: TechnologyEra.strategy,
        baseCost: 30,
        prerequisites: [TechnologyId.administration],
        effects: [MaxControlledHexesBonus(1)],
        treePosition: TechnologyTreePosition(column: 5, row: 0),
      ),
      TechnologyId.fortifications: TechnologyDefinition(
        id: TechnologyId.fortifications,
        name: 'Fortifications',
        description: 'Improves city defense.',
        era: TechnologyEra.industry,
        baseCost: 26,
        prerequisites: [TechnologyId.militaryOrganization],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.walls)],
        effects: [CityDefenseBonus(2)],
        treePosition: TechnologyTreePosition(column: 4, row: 8),
      ),
      TechnologyId.strategy: TechnologyDefinition(
        id: TechnologyId.strategy,
        name: 'Strategy',
        description: 'Unlocks Generals and improves late-game army durability.',
        era: TechnologyEra.strategy,
        baseCost: 30,
        prerequisites: [TechnologyId.logistics],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.warCollege),
          UnlockUnitType(GameUnitType.commander),
        ],
        effects: [
          ArmyStrengthMultiplier(0.10),
          ArmyCombatStatsBonus(defense: 1, hp: 2),
        ],
        treePosition: TechnologyTreePosition(column: 5, row: 9),
      ),
      TechnologyId.specialization: TechnologyDefinition(
        id: TechnologyId.specialization,
        name: 'Specialization',
        description: 'Unlocks city specializations and adds late city science.',
        era: TechnologyEra.strategy,
        baseCost: 32,
        prerequisites: [TechnologyId.administration, TechnologyId.economy],
        effects: [CityScienceBonus(1)],
        treePosition: TechnologyTreePosition(column: 5, row: 2),
      ),
      TechnologyId.scientificMethod: TechnologyDefinition(
        id: TechnologyId.scientificMethod,
        name: 'Scientific Method',
        description: 'Prepares late science, laboratories, and projects.',
        era: TechnologyEra.strategy,
        baseCost: 34,
        prerequisites: [TechnologyId.education, TechnologyId.machinery],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.observatory),
          UnlockCityBuilding(CityBuildingUnlockId.laboratory),
          UnlockWonder(WonderType.nationalObservatory),
        ],
        treePosition: TechnologyTreePosition(column: 6, row: 0),
      ),
      TechnologyId.steamPower: TechnologyDefinition(
        id: TechnologyId.steamPower,
        name: 'Steam Power',
        description: 'Opens rail logistics and steam-driven industry.',
        era: TechnologyEra.strategy,
        baseCost: 34,
        prerequisites: [TechnologyId.steel, TechnologyId.machinery],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.railDepot),
          UnlockWonder(WonderType.motherFactory),
        ],
        treePosition: TechnologyTreePosition(column: 6, row: 4),
      ),
      TechnologyId.electricity: TechnologyDefinition(
        id: TechnologyId.electricity,
        name: 'Electricity',
        description: 'Adds energy infrastructure and information reach.',
        era: TechnologyEra.strategy,
        baseCost: 36,
        prerequisites: [TechnologyId.scientificMethod, TechnologyId.steamPower],
        unlocks: [UnlockCityBuilding(CityBuildingUnlockId.powerPlant)],
        treePosition: TechnologyTreePosition(column: 7, row: 1),
      ),
      TechnologyId.combustion: TechnologyDefinition(
        id: TechnologyId.combustion,
        name: 'Combustion',
        description: 'Makes oil strategic and unlocks modern mobility.',
        era: TechnologyEra.strategy,
        baseCost: 38,
        prerequisites: [TechnologyId.steel, TechnologyId.steamPower],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.refinery),
          UnlockFieldImprovement(FieldImprovementType.oilWell),
          UnlockUnitType(GameUnitType.fieldCannon),
          UnlockUnitType(GameUnitType.rifleman),
        ],
        treePosition: TechnologyTreePosition(column: 7, row: 4),
      ),
      TechnologyId.flight: TechnologyDefinition(
        id: TechnologyId.flight,
        name: 'Flight',
        description:
            'Adds aircraft, reconnaissance, aluminium extraction, and force projection.',
        era: TechnologyEra.strategy,
        baseCost: 40,
        prerequisites: [TechnologyId.combustion, TechnologyId.scientificMethod],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.airfield),
          UnlockFieldImprovement(FieldImprovementType.bauxiteMine),
          UnlockUnitType(GameUnitType.reconPlane),
        ],
        treePosition: TechnologyTreePosition(column: 8, row: 2),
      ),
      TechnologyId.massProduction: TechnologyDefinition(
        id: TechnologyId.massProduction,
        name: 'Mass Production',
        description: 'Creates the final stage of industrial production.',
        era: TechnologyEra.strategy,
        baseCost: 42,
        prerequisites: [TechnologyId.combustion, TechnologyId.electricity],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.assemblyPlant),
          UnlockCityBuilding(CityBuildingUnlockId.worldFairGrounds),
          UnlockUnitType(GameUnitType.tank),
        ],
        treePosition: TechnologyTreePosition(column: 8, row: 5),
      ),
      TechnologyId.radio: TechnologyDefinition(
        id: TechnologyId.radio,
        name: 'Radio',
        description: 'Improves communication, visibility, and influence.',
        era: TechnologyEra.strategy,
        baseCost: 40,
        prerequisites: [TechnologyId.electricity, TechnologyId.flight],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.broadcastTower),
          UnlockWonder(WonderType.grandExposition),
        ],
        treePosition: TechnologyTreePosition(column: 9, row: 2),
      ),
      TechnologyId.nuclearPhysics: TechnologyDefinition(
        id: TechnologyId.nuclearPhysics,
        name: 'Nuclear Physics',
        description: 'Opens uranium, reactors, and final late projects.',
        era: TechnologyEra.strategy,
        baseCost: 48,
        prerequisites: [
          TechnologyId.scientificMethod,
          TechnologyId.electricity,
        ],
        unlocks: [
          UnlockCityBuilding(CityBuildingUnlockId.reactor),
          UnlockFieldImprovement(FieldImprovementType.uraniumMine),
          UnlockWonder(WonderType.svalbardSeedVault),
        ],
        treePosition: TechnologyTreePosition(column: 9, row: 0),
      ),
    };
