import 'package:aonw_core/game/domain/city/field_improvement_type.dart';
import 'package:aonw_core/game/domain/technology/technology_boost.dart';
import 'package:aonw_core/game/domain/technology/technology_definition.dart';
import 'package:aonw_core/game/domain/technology/technology_effect.dart';
import 'package:aonw_core/game/domain/technology/technology_era.dart';
import 'package:aonw_core/game/domain/technology/technology_id.dart';
import 'package:aonw_core/game/domain/technology/technology_tree_position.dart';
import 'package:aonw_core/game/domain/technology/technology_unlock.dart';
import 'package:aonw_core/game/domain/unit.dart';
import 'package:aonw_core/map/domain/terrain_type.dart';

abstract final class TechnologyCatalog {
  static const standard = <TechnologyId, TechnologyDefinition>{
    TechnologyId.agriculture: TechnologyDefinition(
      id: TechnologyId.agriculture,
      name: 'Agriculture',
      description:
          'Unlocks reliable food improvements and fruit orchards for early growth.',
      era: TechnologyEra.foundation,
      baseCost: 6,
      unlocks: [
        UnlockFieldImprovement(FieldImprovementType.farm),
        UnlockFieldImprovement(FieldImprovementType.riverFarm),
        UnlockFieldImprovement(FieldImprovementType.orchard),
      ],
      boosts: [
        TechnologyBoostDefinition(
          condition: ControlsAnyResource({
            ResourceType.wheat,
            ResourceType.rice,
          }),
          discount: 0.25,
          label: 'Wheat or rice',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 0, row: 0),
    ),
    TechnologyId.woodworking: TechnologyDefinition(
      id: TechnologyId.woodworking,
      name: 'Woodworking',
      description: 'Turns forests into early production opportunities.',
      era: TechnologyEra.settlement,
      baseCost: 6,
      prerequisites: [TechnologyId.mining],
      unlocks: [UnlockFieldImprovement(FieldImprovementType.lumberMill)],
      treePosition: TechnologyTreePosition(column: 1, row: 4),
    ),
    TechnologyId.mining: TechnologyDefinition(
      id: TechnologyId.mining,
      name: 'Mining',
      description:
          'Unlocks mines, mineral prospecting, and starts the production branch.',
      era: TechnologyEra.foundation,
      baseCost: 6,
      unlocks: [
        UnlockFieldImprovement(FieldImprovementType.mine),
        UnlockFieldImprovement(FieldImprovementType.prospectorCamp),
      ],
      boosts: [
        TechnologyBoostDefinition(
          condition: ControlsAnyResource({
            ResourceType.iron,
            ResourceType.marble,
          }),
          discount: 0.25,
          label: 'Iron or marble',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 0, row: 4),
    ),
    TechnologyId.animalHusbandry: TechnologyDefinition(
      id: TechnologyId.animalHusbandry,
      name: 'Animal Husbandry',
      description: 'Unlocks pasture improvements and the cavalry branch.',
      era: TechnologyEra.settlement,
      baseCost: 6,
      prerequisites: [TechnologyId.agriculture],
      unlocks: [UnlockFieldImprovement(FieldImprovementType.pasture)],
      treePosition: TechnologyTreePosition(column: 1, row: 0),
    ),
    TechnologyId.hunting: TechnologyDefinition(
      id: TechnologyId.hunting,
      name: 'Hunting',
      description: 'Unlocks camps for forest and wildlife resources.',
      era: TechnologyEra.foundation,
      baseCost: 7,
      unlocks: [
        UnlockFieldImprovement(FieldImprovementType.camp),
        UnlockUnitType(GameUnitType.archer),
      ],
      treePosition: TechnologyTreePosition(column: 0, row: 8),
    ),
    TechnologyId.fishing: TechnologyDefinition(
      id: TechnologyId.fishing,
      name: 'Fishing',
      description: 'Unlocks coastal food improvements.',
      era: TechnologyEra.settlement,
      baseCost: 6,
      prerequisites: [TechnologyId.hunting],
      unlocks: [UnlockFieldImprovement(FieldImprovementType.fishingBoats)],
      boosts: [
        TechnologyBoostDefinition(
          condition: ControlsResource(ResourceType.fish),
          discount: 0.25,
          label: 'Fish',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 1, row: 9),
    ),
    TechnologyId.craftsmanship: TechnologyDefinition(
      id: TechnologyId.craftsmanship,
      name: 'Craftsmanship',
      description: 'Unlocks early urban production.',
      era: TechnologyEra.settlement,
      baseCost: 7,
      prerequisites: [TechnologyId.mining],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.workshop)],
      treePosition: TechnologyTreePosition(column: 1, row: 5),
    ),
    TechnologyId.trade: TechnologyDefinition(
      id: TechnologyId.trade,
      name: 'Trade',
      description:
          'Unlocks the first gold-focused city building and field trade.',
      era: TechnologyEra.settlement,
      baseCost: 7,
      prerequisites: [TechnologyId.agriculture],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.merchantHall),
        UnlockUnitType(GameUnitType.merchant),
        UnlockFieldImprovement(FieldImprovementType.vineyard),
        UnlockFieldImprovement(FieldImprovementType.tradingPost),
      ],
      treePosition: TechnologyTreePosition(column: 1, row: 1),
    ),
    TechnologyId.storage: TechnologyDefinition(
      id: TechnologyId.storage,
      name: 'Storage',
      description: 'Improves food retention and city stability.',
      era: TechnologyEra.expansion,
      baseCost: 11,
      prerequisites: [TechnologyId.agriculture],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.storehouse)],
      boosts: [
        TechnologyBoostDefinition(
          condition: HasImprovementCount(
            improvementType: FieldImprovementType.farm,
            count: 2,
          ),
          discount: 0.25,
          label: '2 farms',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 0),
    ),
    TechnologyId.waterEngineering: TechnologyDefinition(
      id: TechnologyId.waterEngineering,
      name: 'Water Engineering',
      description: 'Adds river-based growth and production options.',
      era: TechnologyEra.expansion,
      baseCost: 12,
      prerequisites: [TechnologyId.agriculture],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.waterMill)],
      treePosition: TechnologyTreePosition(column: 2, row: 1),
    ),
    TechnologyId.stoneworking: TechnologyDefinition(
      id: TechnologyId.stoneworking,
      name: 'Stoneworking',
      description: 'Unlocks quarrying and stone city development.',
      era: TechnologyEra.expansion,
      baseCost: 13,
      prerequisites: [TechnologyId.mining],
      unlocks: [
        UnlockFieldImprovement(FieldImprovementType.quarry),
        UnlockCityBuilding(CityBuildingUnlockId.stonemason),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 4),
    ),
    TechnologyId.militaryOrganization: TechnologyDefinition(
      id: TechnologyId.militaryOrganization,
      name: 'Military Organization',
      description: 'Unlocks the first military city infrastructure and drills.',
      era: TechnologyEra.expansion,
      baseCost: 13,
      prerequisites: [TechnologyId.hunting],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.barracks),
        UnlockCityBuilding(CityBuildingUnlockId.armory),
        UnlockUnitType(GameUnitType.spearman),
      ],
      effects: [ArmyCombatStatsBonus(hp: 1)],
      treePosition: TechnologyTreePosition(column: 2, row: 8),
    ),
    TechnologyId.advancedTrade: TechnologyDefinition(
      id: TechnologyId.advancedTrade,
      name: 'Advanced Trade',
      description: 'Unlocks stronger gold and science economy.',
      era: TechnologyEra.expansion,
      baseCost: 14,
      prerequisites: [TechnologyId.trade],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.marketplace),
        UnlockFieldImprovement(FieldImprovementType.plantation),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 2),
    ),
    TechnologyId.construction: TechnologyDefinition(
      id: TechnologyId.construction,
      name: 'Construction',
      description: 'Unlocks housing and a path toward administration.',
      era: TechnologyEra.expansion,
      baseCost: 13,
      prerequisites: [TechnologyId.craftsmanship],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.housing)],
      boosts: [
        TechnologyBoostDefinition(
          condition: HasAnyImprovement(FieldImprovementType.mine),
          discount: 0.25,
          label: 'Mine',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 5),
    ),
    TechnologyId.navigation: TechnologyDefinition(
      id: TechnologyId.navigation,
      name: 'Navigation',
      description: 'Unlocks coastal city infrastructure and pearl diving.',
      era: TechnologyEra.expansion,
      baseCost: 12,
      prerequisites: [TechnologyId.fishing],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.port),
        UnlockFieldImprovement(FieldImprovementType.pearlDivers),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 9),
    ),
    TechnologyId.irrigation: TechnologyDefinition(
      id: TechnologyId.irrigation,
      name: 'Irrigation',
      description: 'Turns water control into a mature growth branch.',
      era: TechnologyEra.specialization,
      baseCost: 18,
      prerequisites: [TechnologyId.waterEngineering],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.aqueduct)],
      treePosition: TechnologyTreePosition(column: 3, row: 0),
    ),
    TechnologyId.banking: TechnologyDefinition(
      id: TechnologyId.banking,
      name: 'Banking',
      description: 'Turns market trade into stored city wealth.',
      era: TechnologyEra.specialization,
      baseCost: 19,
      prerequisites: [TechnologyId.advancedTrade],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.bank)],
      treePosition: TechnologyTreePosition(column: 3, row: 2),
    ),
    TechnologyId.engineering: TechnologyDefinition(
      id: TechnologyId.engineering,
      name: 'Engineering',
      description: 'Specializes construction into stronger infrastructure.',
      era: TechnologyEra.specialization,
      baseCost: 19,
      prerequisites: [TechnologyId.construction],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.buildersGuild)],
      treePosition: TechnologyTreePosition(column: 3, row: 5),
    ),
    TechnologyId.metallurgy: TechnologyDefinition(
      id: TechnologyId.metallurgy,
      name: 'Metallurgy',
      description: 'Unlocks forge infrastructure and metal production.',
      era: TechnologyEra.specialization,
      baseCost: 20,
      prerequisites: [TechnologyId.stoneworking],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.forge)],
      treePosition: TechnologyTreePosition(column: 3, row: 4),
    ),
    TechnologyId.horsebackRiding: TechnologyDefinition(
      id: TechnologyId.horsebackRiding,
      name: 'Horseback Riding',
      description:
          'Unlocks stable infrastructure, horse ranches, and cavalry growth.',
      era: TechnologyEra.specialization,
      baseCost: 18,
      prerequisites: [TechnologyId.animalHusbandry, TechnologyId.hunting],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.stable),
        UnlockFieldImprovement(FieldImprovementType.horseRanch),
        UnlockUnitType(GameUnitType.cavalry),
      ],
      boosts: [
        TechnologyBoostDefinition(
          condition: ControlsResource(ResourceType.horses),
          discount: 0.25,
          label: 'Horses',
        ),
      ],
      treePosition: TechnologyTreePosition(column: 3, row: 8),
    ),
    TechnologyId.shipbuilding: TechnologyDefinition(
      id: TechnologyId.shipbuilding,
      name: 'Shipbuilding',
      description: 'Extends exploration into coastal city development.',
      era: TechnologyEra.specialization,
      baseCost: 18,
      prerequisites: [TechnologyId.navigation],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.lighthouse)],
      treePosition: TechnologyTreePosition(column: 3, row: 10),
    ),
    TechnologyId.writing: TechnologyDefinition(
      id: TechnologyId.writing,
      name: 'Writing',
      description: 'Starts formal knowledge, law, and administration.',
      era: TechnologyEra.settlement,
      baseCost: 8,
      prerequisites: [TechnologyId.agriculture],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.archive)],
      treePosition: TechnologyTreePosition(column: 1, row: 2),
    ),
    TechnologyId.mathematics: TechnologyDefinition(
      id: TechnologyId.mathematics,
      name: 'Mathematics',
      description:
          'Connects science with territory planning and infrastructure.',
      era: TechnologyEra.expansion,
      baseCost: 15,
      prerequisites: [TechnologyId.writing, TechnologyId.construction],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.surveyorsOffice)],
      treePosition: TechnologyTreePosition(column: 2, row: 3),
    ),
    TechnologyId.medicine: TechnologyDefinition(
      id: TechnologyId.medicine,
      name: 'Medicine',
      description: 'Improves health and long-term growth in larger cities.',
      era: TechnologyEra.expansion,
      baseCost: 16,
      prerequisites: [TechnologyId.writing, TechnologyId.storage],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.apothecary),
        UnlockCityBuilding(CityBuildingUnlockId.publicBaths),
        UnlockCityBuilding(CityBuildingUnlockId.hospital),
      ],
      treePosition: TechnologyTreePosition(column: 2, row: 6),
    ),
    TechnologyId.civilService: TechnologyDefinition(
      id: TechnologyId.civilService,
      name: 'Civil Service',
      description: 'Makes large empires easier to govern and stabilize.',
      era: TechnologyEra.specialization,
      baseCost: 22,
      prerequisites: [TechnologyId.administration],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.courthouse)],
      treePosition: TechnologyTreePosition(column: 4, row: 1),
    ),
    TechnologyId.siegecraft: TechnologyDefinition(
      id: TechnologyId.siegecraft,
      name: 'Siegecraft',
      description: 'Unlocks siege pressure against fortified cities.',
      era: TechnologyEra.specialization,
      baseCost: 22,
      prerequisites: [
        TechnologyId.militaryOrganization,
        TechnologyId.engineering,
      ],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.siegeWorkshop),
        UnlockUnitType(GameUnitType.catapult),
      ],
      treePosition: TechnologyTreePosition(column: 4, row: 10),
    ),
    TechnologyId.cartography: TechnologyDefinition(
      id: TechnologyId.cartography,
      name: 'Cartography',
      description: 'Improves exploration, maps, and coastal reach.',
      era: TechnologyEra.specialization,
      baseCost: 20,
      prerequisites: [TechnologyId.navigation],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.mapRoom),
        UnlockUnitType(GameUnitType.scoutShip),
      ],
      treePosition: TechnologyTreePosition(column: 3, row: 11),
    ),
    TechnologyId.guilds: TechnologyDefinition(
      id: TechnologyId.guilds,
      name: 'Guilds',
      description: 'Adds a production stage between workshop and industry.',
      era: TechnologyEra.specialization,
      baseCost: 21,
      prerequisites: [TechnologyId.craftsmanship, TechnologyId.trade],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.artisansGuild),
        UnlockCityBuilding(CityBuildingUnlockId.masterWorkshop),
      ],
      treePosition: TechnologyTreePosition(column: 3, row: 6),
    ),
    TechnologyId.law: TechnologyDefinition(
      id: TechnologyId.law,
      name: 'Law',
      description: 'Adds order, policy, and civic control to cities.',
      era: TechnologyEra.specialization,
      baseCost: 22,
      prerequisites: [TechnologyId.writing, TechnologyId.administration],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.court)],
      treePosition: TechnologyTreePosition(column: 4, row: 3),
    ),
    TechnologyId.education: TechnologyDefinition(
      id: TechnologyId.education,
      name: 'Education',
      description: 'Builds the full science path for developed cities.',
      era: TechnologyEra.specialization,
      baseCost: 24,
      prerequisites: [TechnologyId.writing, TechnologyId.mathematics],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.academy),
        UnlockCityBuilding(CityBuildingUnlockId.university),
      ],
      treePosition: TechnologyTreePosition(column: 4, row: 0),
    ),
    TechnologyId.ironWorking: TechnologyDefinition(
      id: TechnologyId.ironWorking,
      name: 'Iron Working',
      description: 'Improves production from controlled iron.',
      era: TechnologyEra.industry,
      baseCost: 20,
      prerequisites: [TechnologyId.metallurgy],
      effects: [
        StrategicResourceProductionBonus(
          resourceType: ResourceType.iron,
          production: 1,
        ),
      ],
      treePosition: TechnologyTreePosition(column: 4, row: 4),
    ),
    TechnologyId.coalMining: TechnologyDefinition(
      id: TechnologyId.coalMining,
      name: 'Coal Mining',
      description:
          'Improves production from controlled coal and unlocks coal shafts.',
      era: TechnologyEra.industry,
      baseCost: 20,
      prerequisites: [TechnologyId.metallurgy],
      unlocks: [UnlockFieldImprovement(FieldImprovementType.coalShaft)],
      effects: [
        StrategicResourceProductionBonus(
          resourceType: ResourceType.coal,
          production: 1,
        ),
      ],
      treePosition: TechnologyTreePosition(column: 4, row: 5),
    ),
    TechnologyId.machinery: TechnologyDefinition(
      id: TechnologyId.machinery,
      name: 'Machinery',
      description: 'Converts engineering knowledge into heavy production.',
      era: TechnologyEra.industry,
      baseCost: 23,
      prerequisites: [TechnologyId.engineering],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.factory)],
      treePosition: TechnologyTreePosition(column: 4, row: 6),
    ),
    TechnologyId.urbanPlanning: TechnologyDefinition(
      id: TechnologyId.urbanPlanning,
      name: 'Urban Planning',
      description: 'Develops large cities and more deliberate borders.',
      era: TechnologyEra.industry,
      baseCost: 28,
      prerequisites: [TechnologyId.engineering, TechnologyId.civilService],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.planningOffice)],
      treePosition: TechnologyTreePosition(column: 5, row: 5),
    ),
    TechnologyId.navalDoctrine: TechnologyDefinition(
      id: TechnologyId.navalDoctrine,
      name: 'Naval Doctrine',
      description: 'Turns ports into centers of fleet projection.',
      era: TechnologyEra.industry,
      baseCost: 28,
      prerequisites: [TechnologyId.shipbuilding, TechnologyId.cartography],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.shipyard),
        UnlockCityBuilding(CityBuildingUnlockId.dryDock),
        UnlockCityBuilding(CityBuildingUnlockId.navalAcademy),
        UnlockCityBuilding(CityBuildingUnlockId.harborCustoms),
        UnlockUnitType(GameUnitType.warship),
      ],
      treePosition: TechnologyTreePosition(column: 5, row: 11),
    ),
    TechnologyId.steel: TechnologyDefinition(
      id: TechnologyId.steel,
      name: 'Steel',
      description: 'Introduces heavy industry and stronger front-line troops.',
      era: TechnologyEra.industry,
      baseCost: 30,
      prerequisites: [TechnologyId.ironWorking, TechnologyId.coalMining],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.steelworks),
        UnlockUnitType(GameUnitType.heavyInfantry),
      ],
      treePosition: TechnologyTreePosition(column: 5, row: 4),
    ),
    TechnologyId.bureaucracy: TechnologyDefinition(
      id: TechnologyId.bureaucracy,
      name: 'Bureaucracy',
      description: 'Adds a large civic goal after administration.',
      era: TechnologyEra.industry,
      baseCost: 30,
      prerequisites: [TechnologyId.civilService, TechnologyId.economy],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.governorsOffice),
        UnlockCityBuilding(CityBuildingUnlockId.ministries),
        UnlockCityBuilding(CityBuildingUnlockId.museum),
        UnlockCityBuilding(CityBuildingUnlockId.parliament),
      ],
      treePosition: TechnologyTreePosition(column: 5, row: 1),
    ),
    TechnologyId.nationalism: TechnologyDefinition(
      id: TechnologyId.nationalism,
      name: 'Nationalism',
      description: 'Links border defense, mobilization, and empire identity.',
      era: TechnologyEra.strategy,
      baseCost: 32,
      prerequisites: [TechnologyId.fortifications, TechnologyId.tactics],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.conscriptionOffice),
        UnlockCityBuilding(CityBuildingUnlockId.borderFort),
        UnlockCityBuilding(CityBuildingUnlockId.citadel),
      ],
      treePosition: TechnologyTreePosition(column: 5, row: 8),
    ),
    TechnologyId.administration: TechnologyDefinition(
      id: TechnologyId.administration,
      name: 'Administration',
      description: 'Unlocks civic buildings for mature cities.',
      era: TechnologyEra.specialization,
      baseCost: 20,
      prerequisites: [TechnologyId.construction, TechnologyId.advancedTrade],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.townHall),
        UnlockCityBuilding(CityBuildingUnlockId.monument),
      ],
      treePosition: TechnologyTreePosition(column: 3, row: 1),
    ),
    TechnologyId.logistics: TechnologyDefinition(
      id: TechnologyId.logistics,
      name: 'Logistics',
      description: 'Improves army production throughput.',
      era: TechnologyEra.specialization,
      baseCost: 19,
      prerequisites: [TechnologyId.militaryOrganization],
      effects: [ArmyProductionMultiplier(0.15)],
      treePosition: TechnologyTreePosition(column: 3, row: 9),
    ),
    TechnologyId.tactics: TechnologyDefinition(
      id: TechnologyId.tactics,
      name: 'Tactics',
      description: 'Turns logistics into better battlefield coordination.',
      era: TechnologyEra.industry,
      baseCost: 23,
      prerequisites: [TechnologyId.logistics],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.trainingGrounds)],
      effects: [ArmyCombatStatsBonus(attack: 1, defense: 1)],
      treePosition: TechnologyTreePosition(column: 4, row: 9),
    ),
    TechnologyId.economy: TechnologyDefinition(
      id: TechnologyId.economy,
      name: 'Economy',
      description: 'Improves global gold output.',
      era: TechnologyEra.industry,
      baseCost: 26,
      prerequisites: [TechnologyId.banking],
      effects: [GlobalGoldMultiplier(0.10)],
      treePosition: TechnologyTreePosition(column: 4, row: 2),
    ),
    TechnologyId.urbanization: TechnologyDefinition(
      id: TechnologyId.urbanization,
      name: 'Urbanization',
      description: 'Raises the long-term city growth ceiling.',
      era: TechnologyEra.strategy,
      baseCost: 30,
      prerequisites: [TechnologyId.administration],
      effects: [MaxControlledHexesBonus(1)],
      treePosition: TechnologyTreePosition(column: 5, row: 0),
    ),
    TechnologyId.fortifications: TechnologyDefinition(
      id: TechnologyId.fortifications,
      name: 'Fortifications',
      description: 'Improves city defense.',
      era: TechnologyEra.industry,
      baseCost: 26,
      prerequisites: [TechnologyId.militaryOrganization],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.walls)],
      effects: [CityDefenseBonus(2)],
      treePosition: TechnologyTreePosition(column: 4, row: 8),
    ),
    TechnologyId.strategy: TechnologyDefinition(
      id: TechnologyId.strategy,
      name: 'Strategy',
      description: 'Unlocks Generals and improves late-game army durability.',
      era: TechnologyEra.strategy,
      baseCost: 30,
      prerequisites: [TechnologyId.logistics],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.warCollege),
        UnlockUnitType(GameUnitType.commander),
      ],
      effects: [
        ArmyStrengthMultiplier(0.10),
        ArmyCombatStatsBonus(defense: 1, hp: 2),
      ],
      treePosition: TechnologyTreePosition(column: 5, row: 9),
    ),
    TechnologyId.specialization: TechnologyDefinition(
      id: TechnologyId.specialization,
      name: 'Specialization',
      description: 'Unlocks city specializations and adds late city science.',
      era: TechnologyEra.strategy,
      baseCost: 32,
      prerequisites: [TechnologyId.administration, TechnologyId.economy],
      effects: [CityScienceBonus(1)],
      treePosition: TechnologyTreePosition(column: 5, row: 2),
    ),
    TechnologyId.scientificMethod: TechnologyDefinition(
      id: TechnologyId.scientificMethod,
      name: 'Scientific Method',
      description: 'Prepares late science, laboratories, and projects.',
      era: TechnologyEra.strategy,
      baseCost: 34,
      prerequisites: [TechnologyId.education, TechnologyId.machinery],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.observatory),
        UnlockCityBuilding(CityBuildingUnlockId.laboratory),
      ],
      treePosition: TechnologyTreePosition(column: 6, row: 0),
    ),
    TechnologyId.steamPower: TechnologyDefinition(
      id: TechnologyId.steamPower,
      name: 'Steam Power',
      description: 'Opens rail logistics and steam-driven industry.',
      era: TechnologyEra.strategy,
      baseCost: 34,
      prerequisites: [TechnologyId.steel, TechnologyId.machinery],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.railDepot)],
      treePosition: TechnologyTreePosition(column: 6, row: 4),
    ),
    TechnologyId.electricity: TechnologyDefinition(
      id: TechnologyId.electricity,
      name: 'Electricity',
      description: 'Adds energy infrastructure and information reach.',
      era: TechnologyEra.strategy,
      baseCost: 36,
      prerequisites: [TechnologyId.scientificMethod, TechnologyId.steamPower],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.powerPlant)],
      treePosition: TechnologyTreePosition(column: 7, row: 1),
    ),
    TechnologyId.combustion: TechnologyDefinition(
      id: TechnologyId.combustion,
      name: 'Combustion',
      description: 'Makes oil strategic and unlocks modern mobility.',
      era: TechnologyEra.strategy,
      baseCost: 38,
      prerequisites: [TechnologyId.steel, TechnologyId.steamPower],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.refinery),
        UnlockFieldImprovement(FieldImprovementType.oilWell),
        UnlockUnitType(GameUnitType.fieldCannon),
        UnlockUnitType(GameUnitType.rifleman),
      ],
      treePosition: TechnologyTreePosition(column: 7, row: 4),
    ),
    TechnologyId.flight: TechnologyDefinition(
      id: TechnologyId.flight,
      name: 'Flight',
      description:
          'Adds aircraft, reconnaissance, aluminium extraction, and force projection.',
      era: TechnologyEra.strategy,
      baseCost: 40,
      prerequisites: [TechnologyId.combustion, TechnologyId.scientificMethod],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.airfield),
        UnlockFieldImprovement(FieldImprovementType.bauxiteMine),
        UnlockUnitType(GameUnitType.reconPlane),
      ],
      treePosition: TechnologyTreePosition(column: 8, row: 2),
    ),
    TechnologyId.massProduction: TechnologyDefinition(
      id: TechnologyId.massProduction,
      name: 'Mass Production',
      description: 'Creates the final stage of industrial production.',
      era: TechnologyEra.strategy,
      baseCost: 42,
      prerequisites: [TechnologyId.combustion, TechnologyId.electricity],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.assemblyPlant),
        UnlockCityBuilding(CityBuildingUnlockId.worldFairGrounds),
        UnlockUnitType(GameUnitType.tank),
      ],
      treePosition: TechnologyTreePosition(column: 8, row: 5),
    ),
    TechnologyId.radio: TechnologyDefinition(
      id: TechnologyId.radio,
      name: 'Radio',
      description: 'Improves communication, visibility, and influence.',
      era: TechnologyEra.strategy,
      baseCost: 40,
      prerequisites: [TechnologyId.electricity, TechnologyId.flight],
      unlocks: [UnlockCityBuilding(CityBuildingUnlockId.broadcastTower)],
      treePosition: TechnologyTreePosition(column: 9, row: 2),
    ),
    TechnologyId.nuclearPhysics: TechnologyDefinition(
      id: TechnologyId.nuclearPhysics,
      name: 'Nuclear Physics',
      description: 'Opens uranium, reactors, and final late projects.',
      era: TechnologyEra.strategy,
      baseCost: 48,
      prerequisites: [TechnologyId.scientificMethod, TechnologyId.electricity],
      unlocks: [
        UnlockCityBuilding(CityBuildingUnlockId.reactor),
        UnlockFieldImprovement(FieldImprovementType.uraniumMine),
      ],
      treePosition: TechnologyTreePosition(column: 9, row: 0),
    ),
  };
}
