enum TechnologyId {
  agriculture,
  woodworking,
  mining,
  animalHusbandry,
  hunting,
  fishing,
  craftsmanship,
  trade,
  storage,
  waterEngineering,
  stoneworking,
  militaryOrganization,
  advancedTrade,
  construction,
  navigation,
  irrigation,
  banking,
  engineering,
  metallurgy,
  horsebackRiding,
  ironWorking,
  coalMining,
  machinery,
  administration,
  logistics,
  shipbuilding,
  tactics,
  economy,
  urbanization,
  fortifications,
  strategy,
  specialization,
  writing,
  mathematics,
  medicine,
  civilService,
  siegecraft,
  cartography,
  guilds,
  law,
  education,
  urbanPlanning,
  navalDoctrine,
  steel,
  bureaucracy,
  nationalism,
  scientificMethod,
  steamPower,
  electricity,
  combustion,
  flight,
  massProduction,
  radio,
  nuclearPhysics;

  static TechnologyId fromString(String value) {
    return TechnologyId.values.firstWhere(
      (id) => id.name == value,
      orElse: () => throw ArgumentError('Unknown technology id: $value'),
    );
  }
}
