accepted = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]
ignore-build-dependencies = true
ignore-dev-dependencies = true
ignore-transitive-dependencies = false
private = { ignore = true }
