part of 'balance_pass.dart';

String _markdownReport({
  required _BalancePassOptions options,
  required BalanceBatchReport report,
}) {
  final buffer = StringBuffer()
    ..writeln('# AI Balance Pass')
    ..writeln()
    ..writeln('Generated by `dart run tool/balance_pass.dart`.')
    ..writeln()
    ..writeln('- Games: ${options.games}')
    ..writeln('- Duration: ${_durationLabel(options)}')
    ..writeln('- Turns: ${options.turns}')
    ..writeln('- Difficulty: `${options.difficulty.name}`')
    ..writeln('- MCTS profile: `${options.mctsProfileMode.name}`')
    ..writeln('- Seed: `${options.seed}`')
    ..writeln('- Primary civ: `${options.primaryCiv.name}`')
    ..writeln('- AI civs: `${options.civs.map((civ) => civ.name).join(', ')}`')
    ..writeln()
    ..writeln('## Summary')
    ..writeln()
    ..writeln('- Attempted games: ${report.attemptedGameCount}')
    ..writeln('- Completed games: ${report.gameCount}')
    ..writeln('- Crashes: ${report.crashCount}')
    ..writeln('- Rejected commands: ${report.totalRejectedCommands}')
    ..writeln()
    ..writeln('## MCTS Runtime')
    ..writeln()
    ..writeln(_runtimeTable(report))
    ..writeln()
    ..writeln('## Players')
    ..writeln()
    ..writeln(_playerTable(report))
    ..writeln()
    ..writeln('## Opening Survival')
    ..writeln()
    ..writeln(_openingPlayerTable(report))
    ..writeln()
    ..writeln('## Second-City Recovery')
    ..writeln()
    ..writeln(_expansionPlayerTable(report))
    ..writeln()
    ..writeln('## Civilizations')
    ..writeln()
    ..writeln(_countryTable(report))
    ..writeln()
    ..writeln('## Opening Survival By Civilization')
    ..writeln()
    ..writeln(_openingCountryTable(report))
    ..writeln()
    ..writeln('## Second-City Recovery By Civilization')
    ..writeln()
    ..writeln(_expansionCountryTable(report));

  if (report.failures.isNotEmpty) {
    buffer
      ..writeln()
      ..writeln('## Failures')
      ..writeln()
      ..writeln('| Game | Error |')
      ..writeln('| ---: | --- |');
    for (final failure in report.failures) {
      buffer.writeln('| ${failure.index} | ${_escapeCell(failure.error)} |');
    }
  }

  return buffer.toString();
}

String _openingPlayerTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Player | Civilization | Avg first city | Settler lost | First city lost | Last military lost | Finished no city |',
    )
    ..writeln('| --- | --- | ---: | ---: | ---: | ---: | ---: |');
  for (final playerId in _orderedPlayerIds(report)) {
    final country = _countryForPlayer(report, playerId);
    buffer.writeln(
      '| $playerId | ${country == null ? '-' : _label(country)} | '
      '${_distance(report.averageFirstCityTurn(playerId))} | '
      '${_percent(report.settlerLostBeforeFirstCityRate(playerId))} | '
      '${_percent(report.firstCityLostRate(playerId))} | '
      '${_percent(report.lastMilitaryLostRate(playerId))} | '
      '${_percent(report.finishedWithoutCityRate(playerId))} |',
    );
  }
  return buffer.toString();
}

String _playerTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Player | Civilization | Win rate | Cities | City dist | Min dist | Units | Attacks | Techs | Science | Gold | Net gold |',
    )
    ..writeln(
      '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    );
  for (final playerId in _orderedPlayerIds(report)) {
    final country = _countryForPlayer(report, playerId);
    buffer.writeln(
      '| $playerId | ${country == null ? '-' : _label(country)} | '
      '${_percent(report.winRate(playerId))} | '
      '${_decimal(report.averageFinalCityCount(playerId))} | '
      '${_distance(report.averageCityCenterDistance(playerId))} | '
      '${_distance(report.averageMinimumCityCenterDistance(playerId))} | '
      '${_decimal(report.averageFinalUnitCount(playerId))} | '
      '${_decimal(report.averageAttackCommands(playerId))} | '
      '${_decimal(report.averageFinalTechnologyCount(playerId))} | '
      '${_decimal(report.averageFinalSciencePerTurn(playerId))} | '
      '${_decimal(report.averageFinalGold(playerId))} | '
      '${_signedDecimal(report.averageFinalNetGoldPerTurn(playerId))} |',
    );
  }
  return buffer.toString();
}

String _expansionPlayerTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Player | Civilization | Avg second city | Second-city rate | Avg third city | Third-city rate | Max cities | Finished <2 cities | Lost 2nd city | City drops | Avg 2nd settler | 1-city no-settler | 1-city settler | Avg 3rd settler | 2-city no-settler | 2-city settler | 2-city units | 2-city buildings | 2-city projects | 2-city attacks |',
    )
    ..writeln(
      '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    );
  for (final playerId in _orderedPlayerIds(report)) {
    final country = _countryForPlayer(report, playerId);
    buffer.writeln(
      '| $playerId | ${country == null ? '-' : _label(country)} | '
      '${_distance(report.averageSecondCityTurn(playerId))} | '
      '${_percent(report.secondCityCompletionRate(playerId))} | '
      '${_distance(report.averageThirdCityTurn(playerId))} | '
      '${_percent(report.thirdCityCompletionRate(playerId))} | '
      '${_decimal(report.averageMaxCityCount(playerId))} | '
      '${_percent(report.finishedBelowTwoCitiesRate(playerId))} | '
      '${_percent(report.secondCityLostAfterFoundingRate(playerId))} | '
      '${_decimal(report.averageCityCountDropCount(playerId))} | '
      '${_distance(report.averageFirstPostCitySettlerTurn(playerId))} | '
      '${_decimal(report.averageOneCityNoSettlerTurns(playerId))} | '
      '${_decimal(report.averageOneCityWithSettlerTurns(playerId))} | '
      '${_distance(report.averageFirstPostSecondCitySettlerTurn(playerId))} | '
      '${_decimal(report.averageTwoCityNoSettlerTurns(playerId))} | '
      '${_decimal(report.averageTwoCityWithSettlerTurns(playerId))} | '
      '${_decimal(report.averageTwoCityStartUnitCommands(playerId))} | '
      '${_decimal(report.averageTwoCityStartBuildingCommands(playerId))} | '
      '${_decimal(report.averageTwoCityStartProjectCommands(playerId))} | '
      '${_decimal(report.averageTwoCityAttackCommands(playerId))} |',
    );
  }
  return buffer.toString();
}

String _openingCountryTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Civilization | Avg first city | Settler lost | First city lost | Last military lost | Finished no city |',
    )
    ..writeln('| --- | ---: | ---: | ---: | ---: | ---: |');
  for (final country in _orderedCountries(report)) {
    buffer.writeln(
      '| ${_label(country)} | '
      '${_distance(report.averageFirstCityTurnForCountry(country))} | '
      '${_percent(report.settlerLostBeforeFirstCityRateForCountry(country))} | '
      '${_percent(report.firstCityLostRateForCountry(country))} | '
      '${_percent(report.lastMilitaryLostRateForCountry(country))} | '
      '${_percent(report.finishedWithoutCityRateForCountry(country))} |',
    );
  }
  return buffer.toString();
}

String _expansionCountryTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Civilization | Avg second city | Second-city rate | Avg third city | Third-city rate | Max cities | Finished <2 cities | Lost 2nd city | City drops | Avg 2nd settler | 1-city no-settler | 1-city settler | Avg 3rd settler | 2-city no-settler | 2-city settler | 2-city units | 2-city buildings | 2-city projects | 2-city attacks |',
    )
    ..writeln(
      '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    );
  for (final country in _orderedCountries(report)) {
    buffer.writeln(
      '| ${_label(country)} | '
      '${_distance(report.averageSecondCityTurnForCountry(country))} | '
      '${_percent(report.secondCityCompletionRateForCountry(country))} | '
      '${_distance(report.averageThirdCityTurnForCountry(country))} | '
      '${_percent(report.thirdCityCompletionRateForCountry(country))} | '
      '${_decimal(report.averageMaxCityCountForCountry(country))} | '
      '${_percent(report.finishedBelowTwoCitiesRateForCountry(country))} | '
      '${_percent(report.secondCityLostAfterFoundingRateForCountry(country))} | '
      '${_decimal(report.averageCityCountDropCountForCountry(country))} | '
      '${_distance(report.averageFirstPostCitySettlerTurnForCountry(country))} | '
      '${_decimal(report.averageOneCityNoSettlerTurnsForCountry(country))} | '
      '${_decimal(report.averageOneCityWithSettlerTurnsForCountry(country))} | '
      '${_distance(report.averageFirstPostSecondCitySettlerTurnForCountry(country))} | '
      '${_decimal(report.averageTwoCityNoSettlerTurnsForCountry(country))} | '
      '${_decimal(report.averageTwoCityWithSettlerTurnsForCountry(country))} | '
      '${_decimal(report.averageTwoCityStartUnitCommandsForCountry(country))} | '
      '${_decimal(report.averageTwoCityStartBuildingCommandsForCountry(country))} | '
      '${_decimal(report.averageTwoCityStartProjectCommandsForCountry(country))} | '
      '${_decimal(report.averageTwoCityAttackCommandsForCountry(country))} |',
    );
  }
  return buffer.toString();
}

String _countryTable(BalanceBatchReport report) {
  final buffer = StringBuffer()
    ..writeln(
      '| Civilization | Win rate | Cities | City dist | Min dist | Units | Attacks | Techs | Science | Gold | Net gold |',
    )
    ..writeln(
      '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
    );
  for (final country in _orderedCountries(report)) {
    buffer.writeln(
      '| ${_label(country)} | '
      '${_percent(report.winRateForCountry(country))} | '
      '${_decimal(report.averageFinalCityCountForCountry(country))} | '
      '${_distance(report.averageCityCenterDistanceForCountry(country))} | '
      '${_distance(report.averageMinimumCityCenterDistanceForCountry(country))} | '
      '${_decimal(report.averageFinalUnitCountForCountry(country))} | '
      '${_decimal(report.averageAttackCommandsForCountry(country))} | '
      '${_decimal(report.averageFinalTechnologyCountForCountry(country))} | '
      '${_decimal(report.averageFinalSciencePerTurnForCountry(country))} | '
      '${_decimal(report.averageFinalGoldForCountry(country))} | '
      '${_signedDecimal(report.averageFinalNetGoldPerTurnForCountry(country))} |',
    );
  }
  return buffer.toString();
}

List<String> _orderedPlayerIds(BalanceBatchReport report) {
  return report.playerIds.toList()..sort();
}

List<PlayerCountry> _orderedCountries(BalanceBatchReport report) {
  return report.countries.toList()
    ..sort((left, right) => left.name.compareTo(right.name));
}

PlayerCountry? _countryForPlayer(BalanceBatchReport report, String playerId) {
  for (final game in report.games) {
    final country = game.countryForPlayer(playerId);
    if (country != null) return country;
  }
  return null;
}

String _percent(double value) => '${(value * 100).toStringAsFixed(1)}%';

String _decimal(double value) => value.toStringAsFixed(1);

String _durationMs(double value) => '${value.toStringAsFixed(1)}ms';

String _signedDecimal(double value) {
  final formatted = value.toStringAsFixed(1);
  return value > 0 ? '+$formatted' : formatted;
}

String _distance(double value) => value == 0 ? '-' : value.toStringAsFixed(1);

String _escapeCell(Object? value) {
  return value.toString().replaceAll('|', r'\|').replaceAll('\n', '<br>');
}

String _durationLabel(_BalancePassOptions options) {
  if (options.rawTurnOverride) return 'raw ${options.turns} turns';
  final minutes = options.gameLength.targetMinutes;
  if (minutes == null) return 'unlimited pace';
  return '$minutes min (~${options.turns} turns at '
      '${GameLengthConfig.estimatedMultiplayerTurnSeconds}s/turn)';
}

String _label(Enum value) {
  final spaced = value.name.replaceAllMapped(
    RegExp(r'(?<=[a-z])([A-Z])'),
    (match) => ' ${match.group(1)}',
  );
  return '${spaced[0].toUpperCase()}${spaced.substring(1)}';
}
