import 'dart:io';

import 'package:aonw_core/ai/simulation/economy_simulation.dart';
import 'package:aonw_core/ai/simulation/score_comeback_telemetry_fixture.dart';
import 'package:aonw_core/domain.dart';

void main(List<String> args) {
  final outputDir = Directory(
    _optionValue(args, '--out') ?? '../../build/reports/ai-telemetry',
  )..createSync(recursive: true);
  final presetTurns = _optionalPositiveIntOption(args, '--turns');
  final playerFindings = StringBuffer();
  final report = StringBuffer()
    ..writeln('# AI Economy Telemetry')
    ..writeln()
    ..writeln('Generated by `dart run tool/economy_simulation.dart`.')
    ..writeln()
    ..writeln(
      '| Preset | Turns | First tech | First building | Second city | '
      'First contact | First combat | Dom threshold | Max dom | Dom hold | '
      'Outcome | Objective action | Final pace | Targets | End targets | '
      'Dead turns | Longest dead streak | Findings | CSV |',
    )
    ..writeln(
      '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- | --- | --- | --- | ---: | ---: | --- | --- |',
    );

  for (final preset in _presets) {
    final result = EconomySimulation.run(
      config: EconomySimulationConfig.forGameLength(
        gameLength: preset.gameLength,
        turns: presetTurns,
        opponents: const [_rival],
      ),
    );
    final csvFile = File(
      '${outputDir.path}/economy-simulation-${preset.id}.csv',
    )..writeAsStringSync('${result.toCsv()}\n');
    final player = _summaryPlayer(result.telemetry);
    final findingCodes = _findingsCellForPlayer(
      result.telemetry,
      player.playerId,
    );

    for (final playerReport in result.telemetry.players.values) {
      playerFindings.writeln(
        '| ${preset.id} | ${playerReport.playerId} | '
        '${_finalPaceCell(playerReport)} | '
        '${_findingsCellForPlayer(result.telemetry, playerReport.playerId)} |',
      );
    }

    report.writeln(
      '| ${preset.id} | ${result.rows.length} | '
      '${_cell(player.firstTechnologyTurn)} | '
      '${_cell(player.firstBuildingTurn)} | '
      '${_cell(player.secondCityTurn)} | '
      '${_cell(player.firstContactTurn)} | '
      '${_cell(player.firstCombatTurn)} | '
      '${_cell(player.firstDominationThresholdTurn)} | '
      '${_percentCell(player.maxDominationControlPercent)} | '
      '${player.maxDominationHoldTurns} | '
      '${_outcomeCell(result.telemetry)} | '
      '${_objectiveActionCell(player)} | '
      '${_finalPaceCell(player)} | '
      '${_targetsCell(preset.targets)} | '
      '${_endTargetsCell(preset.targets)} | '
      '${player.deadTurnCount} | '
      '${player.longestDeadTurnStreak} | '
      '$findingCodes | '
      '[csv](${csvFile.uri.pathSegments.last}) |',
    );
  }

  report
    ..writeln()
    ..writeln('## Preset Player Findings')
    ..writeln()
    ..writeln('| Preset | Player | Final pace | Findings |')
    ..writeln('| --- | --- | --- | --- |')
    ..write(playerFindings.toString());

  final scoreChaserRows = [
    for (final fixture in _scoreChaserFixtures) fixture.evaluate(),
  ];
  final scoreChaserCsvFile = File(
    '${outputDir.path}/score-chaser-objective-actions.csv',
  )..writeAsStringSync('${_scoreChaserCsv(scoreChaserRows)}\n');
  report
    ..writeln()
    ..writeln('## Score Chaser Objective Action')
    ..writeln()
    ..writeln(
      'Controlled fixtures built from `EmpireScoreCalculator`, '
      '`ScorePressureAdvisor`, and '
      '`BalanceTelemetryObjectiveActionDiagnostics.scorePressureSamplesFor`.',
    )
    ..writeln()
    ..writeln(
      '| Scenario | Active score | Leader score | Gap | Advice | Target | CSV |',
    )
    ..writeln('| --- | ---: | ---: | ---: | --- | --- | --- |');
  for (final row in scoreChaserRows) {
    report.writeln(
      '| ${row.label} | ${row.activeScore} | ${row.leaderScore} | '
      '${row.scoreGap} | `${row.advice}` | `${row.target}` | '
      '[csv](${scoreChaserCsvFile.uri.pathSegments.last}) |',
    );
  }

  final scoreComeback = const ScoreComebackTelemetryFixture().run();
  final scoreComebackCsvFile = File(
    '${outputDir.path}/score-comeback-telemetry.csv',
  )..writeAsStringSync('${scoreComeback.toCsv()}\n');
  final scoreComebackPlayer = scoreComeback.telemetry.player(
    ScoreComebackTelemetryFixture.activePlayerId,
  );
  report
    ..writeln()
    ..writeln('## Score Comeback Telemetry')
    ..writeln()
    ..writeln(
      'Controlled score-pressure telemetry window for '
      '`GameLengthConfig.standard60`, generated from real '
      '`EmpireScoreCalculator`, `ScorePressureAdvisor`, and '
      '`BalanceTelemetryAnalyzer` code paths.',
    )
    ..writeln()
    ..writeln('| Outcome | Objective action | CSV |')
    ..writeln('| --- | --- | --- |')
    ..writeln(
      '| ${_outcomeCell(scoreComeback.telemetry)} | '
      '${_objectiveActionCell(scoreComebackPlayer)} | '
      '[csv](${scoreComebackCsvFile.uri.pathSegments.last}) |',
    )
    ..writeln()
    ..writeln(
      '| Turn | Scenario | Active score | Leader score | Gap | Advice | Target | Outcome | CSV |',
    )
    ..writeln('| ---: | --- | ---: | ---: | ---: | --- | --- | --- | --- |');
  for (final row in scoreComeback.rows) {
    report.writeln(
      '| T${row.turn} | ${row.scenarioLabel} | ${row.activeScore} | '
      '${row.leaderScore} | ${row.scoreGap} | '
      '`${row.advice?.name ?? 'none'}` | `${row.target?.name ?? 'none'}` | '
      '${row.outcome.finished ? row.outcome.condition.name : '-'} | '
      '[csv](${scoreComebackCsvFile.uri.pathSegments.last}) |',
    );
  }

  final reportFile = File('${outputDir.path}/ai-telemetry-report.md')
    ..writeAsStringSync(report.toString());

  stdout
    ..writeln('Wrote ${reportFile.path}')
    ..writeln(
      'Wrote ${_presets.length} preset CSV files and '
      '${scoreChaserCsvFile.uri.pathSegments.last}, '
      '${scoreComebackCsvFile.uri.pathSegments.last} to ${outputDir.path}',
    );
}

String _cell(int? value) => value == null ? '-' : 'T$value';

String _outcomeCell(BalanceTelemetryReport report) {
  if (report.victoryTurn == null || report.victoryCondition == null) {
    return '-';
  }
  final winner = report.winnerPlayerId == null
      ? ''
      : ' ${report.winnerPlayerId}';
  return 'T${report.victoryTurn} ${report.victoryCondition!.name}$winner';
}

BalanceTelemetryPlayerReport _summaryPlayer(BalanceTelemetryReport report) {
  final winnerPlayerId = report.winnerPlayerId;
  if (report.victoryCondition != GameOutcomeCondition.score &&
      winnerPlayerId != null &&
      report.players.containsKey(winnerPlayerId)) {
    return report.player(winnerPlayerId);
  }
  return report.player('player_1');
}

String _targetsCell(BalanceTelemetryTuningTargets targets) {
  return [
    'tech<=T${targets.firstTechnologyMaxTurn}',
    'build<=T${targets.firstBuildingMaxTurn}',
    'city<=T${targets.secondCityMaxTurn}',
    'contact<=T${targets.firstContactMaxTurn}',
    'combat<=T${targets.firstCombatMaxTurn}',
    if (targets.dominationThresholdMaxTurn > 0)
      'dom<=T${targets.dominationThresholdMaxTurn}',
  ].join('<br>');
}

String _objectiveActionCell(BalanceTelemetryPlayerReport player) {
  if (player.objectiveActionSampleCount == 0) return '-';
  return [
    '${player.objectiveActionSampleCount} samples',
    'target: ${_countsCell(player.objectiveActionTargetCounts)}',
    'advice: ${_countsCell(player.objectiveActionAdviceCounts)}',
  ].join('<br>');
}

String _findingsCellForPlayer(BalanceTelemetryReport report, String playerId) {
  final codes = [
    for (final finding in report.findings)
      if (finding.playerId == playerId || finding.playerId == null)
        finding.code,
  ];
  return codes.isEmpty ? '-' : codes.join('; ');
}

String _finalPaceCell(BalanceTelemetryPlayerReport player) {
  return [
    'techs:${player.finalTechnologyCount}',
    'science:${_optionalInt(player.finalSciencePerTurn)}/turn',
    'cities:${player.finalCityCount}',
    'units:${player.finalUnitCount}',
    'gold:${_optionalInt(player.finalGold)}',
    'net:${_signedOptionalInt(player.finalNetGoldPerTurn)}/turn',
  ].join('<br>');
}

String _endTargetsCell(BalanceTelemetryTuningTargets targets) {
  final rows = [
    _rangeCell(
      'techs',
      targets.finalTechnologyMinCount,
      targets.finalTechnologyMaxCount,
    ),
    _rangeCell(
      'science',
      targets.finalScienceMinPerTurn,
      targets.finalScienceMaxPerTurn,
      suffix: '/turn',
    ),
    _rangeCell('cities', targets.finalCityMinCount, targets.finalCityMaxCount),
  ].where((row) => row.isNotEmpty);
  return rows.isEmpty ? '-' : rows.join('<br>');
}

String _rangeCell(String label, int min, int max, {String suffix = ''}) {
  if (min <= 0 && max <= 0) return '';
  if (min > 0 && max > 0) return '$label:$min-$max$suffix';
  if (min > 0) return '$label:>=$min$suffix';
  return '$label:<=$max$suffix';
}

String _optionalInt(int? value) => value == null ? '-' : value.toString();

String _signedOptionalInt(int? value) {
  if (value == null) return '-';
  return value >= 0 ? '+$value' : '$value';
}

String _countsCell<K extends Enum>(Map<K, int> counts) {
  if (counts.isEmpty) return '-';
  final entries = counts.entries.toList()
    ..sort((left, right) => left.key.index.compareTo(right.key.index));
  return entries.map((entry) => '${entry.key.name}:${entry.value}').join(', ');
}

String _percentCell(double value) => '${value.toStringAsFixed(1)}%';

String _scoreChaserCsv(List<_ScoreChaserRow> rows) {
  return [
    [
      'scenario',
      'active_score',
      'leader_score',
      'score_gap',
      'advice',
      'target',
    ].join(','),
    for (final row in rows)
      [
        row.id,
        row.activeScore,
        row.leaderScore,
        row.scoreGap,
        row.advice,
        row.target,
      ].map(_csv).join(','),
  ].join('\n');
}

String _csv(Object? value) {
  final text = switch (value) {
    null => '',
    final String text => text,
    final Object value => value.toString(),
  };
  if (!text.contains(',') && !text.contains('"') && !text.contains('\n')) {
    return text;
  }
  return '"${text.replaceAll('"', '""')}"';
}

String? _optionValue(List<String> args, String option) {
  for (var i = 0; i < args.length; i++) {
    final arg = args[i];
    if (arg == option && i + 1 < args.length) return args[i + 1];
    if (arg.startsWith('$option=')) return arg.substring(option.length + 1);
  }
  return null;
}

int? _optionalPositiveIntOption(List<String> args, String option) {
  final value = _optionValue(args, option);
  if (value == null) return null;
  final parsed = int.tryParse(value);
  if (parsed == null || parsed <= 0) {
    throw ArgumentError.value(value, option, 'Must be a positive integer.');
  }
  return parsed;
}

const _rival = Player(
  id: 'player_2',
  name: 'AI Rival',
  colorValue: 0xFF2563EB,
  kind: PlayerKind.ai,
  ai: AiPlayer(strategyId: AiStrategyId.basic, seed: 2002),
);

const _presets = [
  _SimulationPreset(id: 'standard60', gameLength: GameLengthConfig.standard60),
  _SimulationPreset(id: 'normal90', gameLength: GameLengthConfig.normal90),
  _SimulationPreset(id: 'long120', gameLength: GameLengthConfig.long120),
];

final _scoreChaserFixtures = [
  const _ScoreChaserFixture(
    id: 'production_gap',
    label: 'Production gap',
    state: PersistentGameState(
      units: [],
      cities: [
        GameCity(
          id: 'city_1',
          ownerPlayerId: 'player_1',
          name: 'Active',
          center: CityHex(col: 0, row: 0),
        ),
        GameCity(
          id: 'city_2',
          ownerPlayerId: 'player_2',
          name: 'Leader',
          center: CityHex(col: 5, row: 0),
          buildings: {
            CityBuildingType.granary,
            CityBuildingType.monument,
            CityBuildingType.marketplace,
          },
        ),
      ],
    ),
  ),
  _ScoreChaserFixture(
    id: 'research_gap',
    label: 'Research gap',
    state: PersistentGameState(
      units: const [],
      cities: const [
        GameCity(
          id: 'city_1',
          ownerPlayerId: 'player_1',
          name: 'Active',
          center: CityHex(col: 0, row: 0),
          productionQueue: CityProductionQueue.target(
            target: BuildingProductionTarget(CityBuildingType.granary),
            investedProduction: 0,
          ),
        ),
        GameCity(
          id: 'city_2',
          ownerPlayerId: 'player_2',
          name: 'Leader',
          center: CityHex(col: 5, row: 0),
        ),
      ],
      research: ResearchState(
        players: {
          'player_1': PlayerResearchState(),
          'player_2': PlayerResearchState(
            unlockedTechnologyIds: {
              TechnologyId.agriculture,
              TechnologyId.writing,
            },
          ),
        },
      ),
    ),
  ),
  const _ScoreChaserFixture(
    id: 'economy_gap',
    label: 'Economy gap',
    state: PersistentGameState(
      playerGold: {'player_1': 0, 'player_2': 250},
      units: [],
      cities: [
        GameCity(
          id: 'city_1',
          ownerPlayerId: 'player_1',
          name: 'Active',
          center: CityHex(col: 0, row: 0),
        ),
        GameCity(
          id: 'city_2',
          ownerPlayerId: 'player_2',
          name: 'Leader',
          center: CityHex(col: 5, row: 0),
        ),
      ],
    ),
  ),
];

class _SimulationPreset {
  const _SimulationPreset({required this.id, required this.gameLength});

  final String id;
  final GameLengthConfig gameLength;

  BalanceTelemetryTuningTargets get targets {
    return BalanceTelemetryTuningTargets.forPaceProfile(gameLength.paceProfile);
  }
}

class _ScoreChaserFixture {
  const _ScoreChaserFixture({
    required this.id,
    required this.label,
    required this.state,
  });

  final String id;
  final String label;
  final PersistentGameState state;

  _ScoreChaserRow evaluate() {
    const activePlayerId = 'player_1';
    const leaderPlayerId = 'player_2';
    final activeScore = const EmpireScoreCalculator().scoreFor(
      playerId: activePlayerId,
      state: state,
    );
    final leaderScore = const EmpireScoreCalculator().scoreFor(
      playerId: leaderPlayerId,
      state: state,
    );
    final samples =
        BalanceTelemetryObjectiveActionDiagnostics.scorePressureSamplesFor(
          state: state,
          playerIds: const [activePlayerId, leaderPlayerId],
        );
    final sample = samples[activePlayerId];

    return _ScoreChaserRow(
      id: id,
      label: label,
      activeScore: activeScore.total,
      leaderScore: leaderScore.total,
      advice: sample?.advice.name ?? 'none',
      target: sample?.target.name ?? 'none',
    );
  }
}

class _ScoreChaserRow {
  const _ScoreChaserRow({
    required this.id,
    required this.label,
    required this.activeScore,
    required this.leaderScore,
    required this.advice,
    required this.target,
  });

  final String id;
  final String label;
  final int activeScore;
  final int leaderScore;
  final String advice;
  final String target;

  int get scoreGap => leaderScore - activeScore;
}
