import 'package:aonw/game/presentation/formatters/turn_eta.dart';
import 'package:aonw/game/presentation/widgets/city/city_yield_breakdown_panel.dart';
import 'package:aonw/game/presentation/widgets/city/city_yield_breakdown_view_model.dart';
import 'package:aonw/l10n/generated/app_localizations.dart';
import 'package:aonw_core/game/domain/tile_yield.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

const _model = CityYieldBreakdownViewModel(
  totalYield: TileYield(food: 3, production: 4, gold: 1, defense: 0),
  growthLabel: '4/16 food',
  growthEta: TurnEta(turnsRemaining: 3, completionTurn: 7),
  scienceRows: [
    CityScienceBreakdownRow(
      label: 'City base',
      detail: 'Fixed science generated by each city',
      value: 2,
    ),
    CityScienceBreakdownRow(
      label: 'Buildings',
      detail: '1 science building',
      value: 2,
    ),
  ],
  rows: [
    CityYieldBreakdownRow(
      label: 'Center',
      detail: 'Fixed yield from the city center',
      yield: TileYield(food: 2, production: 1, gold: 0, defense: 0),
    ),
    CityYieldBreakdownRow(
      label: 'Workers',
      detail: 'No assigned workers',
      yield: TileYield(food: 0, production: 0, gold: 0, defense: 0),
    ),
  ],
);

void main() {
  testWidgets('CityYieldBreakdownPanel renders total and source rows', (
    tester,
  ) async {
    await tester.pumpWidget(
      const MaterialApp(
        locale: Locale('en'),
        localizationsDelegates: AppLocalizations.localizationsDelegates,
        supportedLocales: AppLocalizations.supportedLocales,
        home: Scaffold(
          body: SizedBox(
            width: 420,
            child: CityYieldBreakdownPanel(model: _model),
          ),
        ),
      ),
    );

    expect(find.text('City economy'), findsOneWidget);
    expect(
      find.text('Real yield/turn • growth 4/16 food • 3 turns • T7'),
      findsOneWidget,
    );
    expect(find.text('Center'), findsOneWidget);
    expect(find.text('Workers'), findsOneWidget);
    expect(find.text('No assigned workers'), findsOneWidget);
    expect(find.text('PRODUCTION SOURCES'), findsOneWidget);
    expect(find.text('SCIENCE SOURCES'), findsOneWidget);
    expect(find.text('City base'), findsOneWidget);
    expect(find.text('Buildings'), findsOneWidget);
  });
}
