use aonw_domain::TechnologyId;
use serde::Serialize;

/// Stable content identity for a technology.
#[allow(missing_docs)]
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum TechnologyKey {
    Agriculture,
    Woodworking,
    Mining,
    AnimalHusbandry,
    Hunting,
    Fishing,
    Craftsmanship,
    Trade,
    Storage,
    WaterEngineering,
    Stoneworking,
    MilitaryOrganization,
    AdvancedTrade,
    Construction,
    Navigation,
    Irrigation,
    Banking,
    Engineering,
    Metallurgy,
    HorsebackRiding,
    IronWorking,
    CoalMining,
    Machinery,
    Administration,
    Logistics,
    Shipbuilding,
    Tactics,
    Economy,
    Urbanization,
    Fortifications,
    Strategy,
    Specialization,
    Writing,
    Mathematics,
    Medicine,
    CivilService,
    Siegecraft,
    Cartography,
    Guilds,
    Law,
    Education,
    UrbanPlanning,
    NavalDoctrine,
    Steel,
    Bureaucracy,
    Nationalism,
    ScientificMethod,
    SteamPower,
    Electricity,
    Combustion,
    Flight,
    MassProduction,
    Radio,
    NuclearPhysics,
}

impl TechnologyKey {
    /// Complete catalog order used by exhaustive checks and clients.
    pub const ALL: [Self; 54] = [
        Self::Agriculture,
        Self::Woodworking,
        Self::Mining,
        Self::AnimalHusbandry,
        Self::Hunting,
        Self::Fishing,
        Self::Craftsmanship,
        Self::Trade,
        Self::Storage,
        Self::WaterEngineering,
        Self::Stoneworking,
        Self::MilitaryOrganization,
        Self::AdvancedTrade,
        Self::Construction,
        Self::Navigation,
        Self::Irrigation,
        Self::Banking,
        Self::Engineering,
        Self::Metallurgy,
        Self::HorsebackRiding,
        Self::IronWorking,
        Self::CoalMining,
        Self::Machinery,
        Self::Administration,
        Self::Logistics,
        Self::Shipbuilding,
        Self::Tactics,
        Self::Economy,
        Self::Urbanization,
        Self::Fortifications,
        Self::Strategy,
        Self::Specialization,
        Self::Writing,
        Self::Mathematics,
        Self::Medicine,
        Self::CivilService,
        Self::Siegecraft,
        Self::Cartography,
        Self::Guilds,
        Self::Law,
        Self::Education,
        Self::UrbanPlanning,
        Self::NavalDoctrine,
        Self::Steel,
        Self::Bureaucracy,
        Self::Nationalism,
        Self::ScientificMethod,
        Self::SteamPower,
        Self::Electricity,
        Self::Combustion,
        Self::Flight,
        Self::MassProduction,
        Self::Radio,
        Self::NuclearPhysics,
    ];

    /// Returns the canonical lower-camel identity used by rule evidence.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Agriculture => "agriculture",
            Self::Woodworking => "woodworking",
            Self::Mining => "mining",
            Self::AnimalHusbandry => "animalHusbandry",
            Self::Hunting => "hunting",
            Self::Fishing => "fishing",
            Self::Craftsmanship => "craftsmanship",
            Self::Trade => "trade",
            Self::Storage => "storage",
            Self::WaterEngineering => "waterEngineering",
            Self::Stoneworking => "stoneworking",
            Self::MilitaryOrganization => "militaryOrganization",
            Self::AdvancedTrade => "advancedTrade",
            Self::Construction => "construction",
            Self::Navigation => "navigation",
            Self::Irrigation => "irrigation",
            Self::Banking => "banking",
            Self::Engineering => "engineering",
            Self::Metallurgy => "metallurgy",
            Self::HorsebackRiding => "horsebackRiding",
            Self::IronWorking => "ironWorking",
            Self::CoalMining => "coalMining",
            Self::Machinery => "machinery",
            Self::Administration => "administration",
            Self::Logistics => "logistics",
            Self::Shipbuilding => "shipbuilding",
            Self::Tactics => "tactics",
            Self::Economy => "economy",
            Self::Urbanization => "urbanization",
            Self::Fortifications => "fortifications",
            Self::Strategy => "strategy",
            Self::Specialization => "specialization",
            Self::Writing => "writing",
            Self::Mathematics => "mathematics",
            Self::Medicine => "medicine",
            Self::CivilService => "civilService",
            Self::Siegecraft => "siegecraft",
            Self::Cartography => "cartography",
            Self::Guilds => "guilds",
            Self::Law => "law",
            Self::Education => "education",
            Self::UrbanPlanning => "urbanPlanning",
            Self::NavalDoctrine => "navalDoctrine",
            Self::Steel => "steel",
            Self::Bureaucracy => "bureaucracy",
            Self::Nationalism => "nationalism",
            Self::ScientificMethod => "scientificMethod",
            Self::SteamPower => "steamPower",
            Self::Electricity => "electricity",
            Self::Combustion => "combustion",
            Self::Flight => "flight",
            Self::MassProduction => "massProduction",
            Self::Radio => "radio",
            Self::NuclearPhysics => "nuclearPhysics",
        }
    }

    /// Maps content identity to the framework-independent domain value.
    #[must_use]
    pub const fn domain(self) -> TechnologyId {
        match self {
            Self::Agriculture => TechnologyId::Agriculture,
            Self::Woodworking => TechnologyId::Woodworking,
            Self::Mining => TechnologyId::Mining,
            Self::AnimalHusbandry => TechnologyId::AnimalHusbandry,
            Self::Hunting => TechnologyId::Hunting,
            Self::Fishing => TechnologyId::Fishing,
            Self::Craftsmanship => TechnologyId::Craftsmanship,
            Self::Trade => TechnologyId::Trade,
            Self::Storage => TechnologyId::Storage,
            Self::WaterEngineering => TechnologyId::WaterEngineering,
            Self::Stoneworking => TechnologyId::Stoneworking,
            Self::MilitaryOrganization => TechnologyId::MilitaryOrganization,
            Self::AdvancedTrade => TechnologyId::AdvancedTrade,
            Self::Construction => TechnologyId::Construction,
            Self::Navigation => TechnologyId::Navigation,
            Self::Irrigation => TechnologyId::Irrigation,
            Self::Banking => TechnologyId::Banking,
            Self::Engineering => TechnologyId::Engineering,
            Self::Metallurgy => TechnologyId::Metallurgy,
            Self::HorsebackRiding => TechnologyId::HorsebackRiding,
            Self::IronWorking => TechnologyId::IronWorking,
            Self::CoalMining => TechnologyId::CoalMining,
            Self::Machinery => TechnologyId::Machinery,
            Self::Administration => TechnologyId::Administration,
            Self::Logistics => TechnologyId::Logistics,
            Self::Shipbuilding => TechnologyId::Shipbuilding,
            Self::Tactics => TechnologyId::Tactics,
            Self::Economy => TechnologyId::Economy,
            Self::Urbanization => TechnologyId::Urbanization,
            Self::Fortifications => TechnologyId::Fortifications,
            Self::Strategy => TechnologyId::Strategy,
            Self::Specialization => TechnologyId::Specialization,
            Self::Writing => TechnologyId::Writing,
            Self::Mathematics => TechnologyId::Mathematics,
            Self::Medicine => TechnologyId::Medicine,
            Self::CivilService => TechnologyId::CivilService,
            Self::Siegecraft => TechnologyId::Siegecraft,
            Self::Cartography => TechnologyId::Cartography,
            Self::Guilds => TechnologyId::Guilds,
            Self::Law => TechnologyId::Law,
            Self::Education => TechnologyId::Education,
            Self::UrbanPlanning => TechnologyId::UrbanPlanning,
            Self::NavalDoctrine => TechnologyId::NavalDoctrine,
            Self::Steel => TechnologyId::Steel,
            Self::Bureaucracy => TechnologyId::Bureaucracy,
            Self::Nationalism => TechnologyId::Nationalism,
            Self::ScientificMethod => TechnologyId::ScientificMethod,
            Self::SteamPower => TechnologyId::SteamPower,
            Self::Electricity => TechnologyId::Electricity,
            Self::Combustion => TechnologyId::Combustion,
            Self::Flight => TechnologyId::Flight,
            Self::MassProduction => TechnologyId::MassProduction,
            Self::Radio => TechnologyId::Radio,
            Self::NuclearPhysics => TechnologyId::NuclearPhysics,
        }
    }
}

/// Research-era cost band.
#[allow(missing_docs)]
#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum TechnologyEra {
    Foundation,
    Settlement,
    Expansion,
    Specialization,
    Industry,
    Strategy,
}
