use super::{
    BOOST_DISCOUNT, Boost, BoostCondition, Building, Effect, Era, Improvement, Key, Resource, Tech,
    Unit, Unlock, Wonder,
};

pub(super) const TECHNOLOGIES: [Tech; 30] = [
    Tech::new(
        Key::Irrigation,
        Era::Specialization,
        18,
        &[Key::WaterEngineering],
        &[Unlock::Building(Building::Aqueduct)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Banking,
        Era::Specialization,
        19,
        &[Key::AdvancedTrade],
        &[
            Unlock::Building(Building::Bank),
            Unlock::Wonder(Wonder::CentralBank),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Engineering,
        Era::Specialization,
        19,
        &[Key::Construction],
        &[Unlock::Building(Building::BuildersGuild)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Metallurgy,
        Era::Specialization,
        20,
        &[Key::Stoneworking],
        &[Unlock::Building(Building::Forge)],
        &[],
        &[],
    ),
    Tech::new(
        Key::HorsebackRiding,
        Era::Specialization,
        18,
        &[Key::AnimalHusbandry, Key::Hunting],
        &[
            Unlock::Building(Building::Stable),
            Unlock::Improvement(Improvement::HorseRanch),
            Unlock::Unit(Unit::Cavalry),
        ],
        &[],
        &[Boost::new(
            BoostCondition::ControlsAnyResource {
                resources: &[Resource::Horses],
            },
            BOOST_DISCOUNT,
        )],
    ),
    Tech::new(
        Key::IronWorking,
        Era::Industry,
        20,
        &[Key::Metallurgy],
        &[],
        &[Effect::StrategicResourceProduction {
            resource: Resource::Iron,
            amount: 1,
        }],
        &[],
    ),
    Tech::new(
        Key::CoalMining,
        Era::Industry,
        20,
        &[Key::Metallurgy],
        &[
            Unlock::Improvement(Improvement::CoalShaft),
            Unlock::ResourceVisibility(Resource::Coal),
        ],
        &[Effect::StrategicResourceProduction {
            resource: Resource::Coal,
            amount: 1,
        }],
        &[],
    ),
    Tech::new(
        Key::Machinery,
        Era::Industry,
        23,
        &[Key::Engineering],
        &[Unlock::Building(Building::Factory)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Administration,
        Era::Specialization,
        20,
        &[Key::Construction, Key::AdvancedTrade],
        &[
            Unlock::Building(Building::TownHall),
            Unlock::Building(Building::Monument),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Logistics,
        Era::Specialization,
        19,
        &[Key::MilitaryOrganization],
        &[],
        &[Effect::ArmyProductionMultiplier {
            basis_points: 1_500,
        }],
        &[],
    ),
    Tech::new(
        Key::Shipbuilding,
        Era::Specialization,
        18,
        &[Key::Navigation],
        &[Unlock::Building(Building::Lighthouse)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Tactics,
        Era::Industry,
        23,
        &[Key::Logistics],
        &[Unlock::Building(Building::TrainingGrounds)],
        &[Effect::ArmyCombatStatsBonus {
            attack: 1,
            defense: 1,
            hit_points: 0,
        }],
        &[],
    ),
    Tech::new(
        Key::Economy,
        Era::Industry,
        26,
        &[Key::Banking],
        &[],
        &[Effect::GlobalGoldMultiplier {
            basis_points: 1_000,
        }],
        &[],
    ),
    Tech::new(
        Key::Urbanization,
        Era::Strategy,
        30,
        &[Key::Administration],
        &[],
        &[Effect::MaxControlledHexesBonus { amount: 1 }],
        &[],
    ),
    Tech::new(
        Key::Fortifications,
        Era::Industry,
        26,
        &[Key::MilitaryOrganization],
        &[Unlock::Building(Building::Walls)],
        &[Effect::CityDefenseBonus { amount: 2 }],
        &[],
    ),
    Tech::new(
        Key::Strategy,
        Era::Strategy,
        30,
        &[Key::Logistics],
        &[
            Unlock::Building(Building::WarCollege),
            Unlock::Unit(Unit::Commander),
        ],
        &[
            Effect::ArmyStrengthMultiplier {
                basis_points: 1_000,
            },
            Effect::ArmyCombatStatsBonus {
                attack: 0,
                defense: 1,
                hit_points: 2,
            },
        ],
        &[],
    ),
    Tech::new(
        Key::Specialization,
        Era::Strategy,
        32,
        &[Key::Administration, Key::Economy],
        &[],
        &[Effect::CityScienceBonus { amount: 1 }],
        &[],
    ),
    Tech::new(
        Key::Writing,
        Era::Settlement,
        8,
        &[Key::Agriculture],
        &[
            Unlock::Building(Building::Archive),
            Unlock::Wonder(Wonder::GreatLibrary),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Mathematics,
        Era::Expansion,
        15,
        &[Key::Writing, Key::Construction],
        &[Unlock::Building(Building::SurveyorsOffice)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Medicine,
        Era::Expansion,
        16,
        &[Key::Writing, Key::Storage],
        &[
            Unlock::Building(Building::Apothecary),
            Unlock::Building(Building::PublicBaths),
            Unlock::Building(Building::Hospital),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::CivilService,
        Era::Specialization,
        22,
        &[Key::Administration],
        &[Unlock::Building(Building::Courthouse)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Siegecraft,
        Era::Specialization,
        22,
        &[Key::MilitaryOrganization, Key::Engineering],
        &[
            Unlock::Building(Building::SiegeWorkshop),
            Unlock::Unit(Unit::Catapult),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Cartography,
        Era::Specialization,
        20,
        &[Key::Navigation],
        &[
            Unlock::Building(Building::MapRoom),
            Unlock::Unit(Unit::ScoutShip),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Guilds,
        Era::Specialization,
        21,
        &[Key::Craftsmanship, Key::Trade],
        &[
            Unlock::Building(Building::ArtisansGuild),
            Unlock::Building(Building::MasterWorkshop),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Law,
        Era::Specialization,
        22,
        &[Key::Writing, Key::Administration],
        &[
            Unlock::Building(Building::Court),
            Unlock::Wonder(Wonder::GrandCathedral),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Education,
        Era::Specialization,
        24,
        &[Key::Writing, Key::Mathematics],
        &[
            Unlock::Building(Building::Academy),
            Unlock::Building(Building::University),
            Unlock::Wonder(Wonder::ImperialUniversity),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::UrbanPlanning,
        Era::Industry,
        28,
        &[Key::Engineering, Key::CivilService],
        &[Unlock::Building(Building::PlanningOffice)],
        &[],
        &[],
    ),
    Tech::new(
        Key::NavalDoctrine,
        Era::Industry,
        28,
        &[Key::Shipbuilding, Key::Cartography],
        &[
            Unlock::Building(Building::Shipyard),
            Unlock::Building(Building::DryDock),
            Unlock::Building(Building::NavalAcademy),
            Unlock::Building(Building::HarborCustoms),
            Unlock::Unit(Unit::Warship),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Steel,
        Era::Industry,
        30,
        &[Key::IronWorking, Key::CoalMining],
        &[
            Unlock::Building(Building::Steelworks),
            Unlock::Unit(Unit::HeavyInfantry),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Bureaucracy,
        Era::Industry,
        30,
        &[Key::CivilService, Key::Economy],
        &[
            Unlock::Building(Building::GovernorsOffice),
            Unlock::Building(Building::Ministries),
            Unlock::Building(Building::Museum),
            Unlock::Building(Building::Parliament),
        ],
        &[],
        &[],
    ),
];
