use super::{Building, Era, Improvement, Key, Resource, Tech, Unit, Unlock, Wonder};

pub(super) const TECHNOLOGIES: [Tech; 9] = [
    Tech::new(
        Key::Nationalism,
        Era::Strategy,
        32,
        &[Key::Fortifications, Key::Tactics],
        &[
            Unlock::Building(Building::ConscriptionOffice),
            Unlock::Building(Building::BorderFort),
            Unlock::Building(Building::Citadel),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::ScientificMethod,
        Era::Strategy,
        34,
        &[Key::Education, Key::Machinery],
        &[
            Unlock::Building(Building::Observatory),
            Unlock::Building(Building::Laboratory),
            Unlock::Wonder(Wonder::NationalObservatory),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::SteamPower,
        Era::Strategy,
        34,
        &[Key::Steel, Key::Machinery],
        &[
            Unlock::Building(Building::RailDepot),
            Unlock::Wonder(Wonder::MotherFactory),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Electricity,
        Era::Strategy,
        36,
        &[Key::ScientificMethod, Key::SteamPower],
        &[Unlock::Building(Building::PowerPlant)],
        &[],
        &[],
    ),
    Tech::new(
        Key::Combustion,
        Era::Strategy,
        38,
        &[Key::Steel, Key::SteamPower],
        &[
            Unlock::Building(Building::Refinery),
            Unlock::Improvement(Improvement::OilWell),
            Unlock::ResourceVisibility(Resource::Oil),
            Unlock::Unit(Unit::FieldCannon),
            Unlock::Unit(Unit::Rifleman),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Flight,
        Era::Strategy,
        40,
        &[Key::Combustion, Key::ScientificMethod],
        &[
            Unlock::Building(Building::Airfield),
            Unlock::Improvement(Improvement::BauxiteMine),
            Unlock::ResourceVisibility(Resource::Aluminium),
            Unlock::Unit(Unit::ReconPlane),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::MassProduction,
        Era::Strategy,
        42,
        &[Key::Combustion, Key::Electricity],
        &[
            Unlock::Building(Building::AssemblyPlant),
            Unlock::Building(Building::WorldFairGrounds),
            Unlock::Unit(Unit::Tank),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::Radio,
        Era::Strategy,
        40,
        &[Key::Electricity, Key::Flight],
        &[
            Unlock::Building(Building::BroadcastTower),
            Unlock::Wonder(Wonder::GrandExposition),
        ],
        &[],
        &[],
    ),
    Tech::new(
        Key::NuclearPhysics,
        Era::Strategy,
        48,
        &[Key::ScientificMethod, Key::Electricity],
        &[
            Unlock::Building(Building::Reactor),
            Unlock::Improvement(Improvement::UraniumMine),
            Unlock::ResourceVisibility(Resource::Uranium),
            Unlock::Wonder(Wonder::SvalbardSeedVault),
        ],
        &[],
        &[],
    ),
];
